import { BarChart3, Eye, Shield, Sparkles, Target, Users } from 'lucide-react';

import type { DataModule } from './model';

const dataCatalogSourceIds = ['ds-027'];

export const coreDataModules: DataModule[] = [
{
    id: 'mkt', name: '市场洞察数据', icon: BarChart3, color: '#C25B6E', page: '/market',
    desc: '看市场模块所需全部数据，覆盖市场规模、趋势、PEST分析、波特五力、海关、品类分析',
    sourceIds: dataCatalogSourceIds,

    tables: [
      {
        id: 't_mkt_size', name: 'market_size_global', desc: '全球婴童/吸奶器市场规模（市场层级与份额分母公开报告口径）',
        updateFreq: '季度',
        upstream: ['Grand View Research', 'Precedence Research', 'Fortune Business Insights'],
        downstream: ['market_trend', 'competitive_landscape'],
        fields: [
          { name: 'scope', type: 'VARCHAR(50)', desc: '口径层级（upper_tam/category_tam/segment_tam/region_share/serviceable_market）', source: '公开研报', required: true },
          { name: 'region', type: 'VARCHAR(50)', desc: '区域（global/北美/非北美合计等）', source: '公开研报或派生', required: true },
          { name: 'category', type: 'VARCHAR(80)', desc: '品类（全球婴童用品/全球吸奶器/穿戴式吸奶器）', source: '公开研报', required: true },
          { name: 'market_size_usd_m', type: 'DECIMAL(12,2)', desc: '市场规模，百万美元', source: 'Grand View Research / Precedence Research / Fortune BI', required: true },
          { name: 'share_pct', type: 'DECIMAL(5,2)', desc: '区域或口径份额 %，仅已复核项填写', source: 'Fortune BI或派生计算', required: false },
          { name: 'cagr_pct', type: 'DECIMAL(5,2)', desc: '年复合增长率 %', source: '公开研报', required: true },
          { name: 'year', type: 'INT', desc: '统计年份', source: '外部研报', required: true },
          { name: 'forecast_to', type: 'INT', desc: '预测截止年份', source: '外部研报', required: true },
          { name: 'source_id', type: 'VARCHAR(20)', desc: '来源登记ID（ds-001/ds-002/ds-044/ds-045）', source: 'source-registry', required: true },
          { name: 'created_at', type: 'TIMESTAMP', desc: '数据入库时间', source: '系统', required: true },
        ],
      },
      {
        id: 't_mkt_trend', name: 'market_trend_monthly', desc: '月度公开兴趣趋势与ERP内部销量代理治理表',
        updateFreq: '月度', upstream: ['Wikimedia Pageviews API', 'Amazon/Vendor Central待授权', 'ERP电商销售统计导出', 'ERP售后销量统计导出', 'ERP零售与渠道UI分页采集'], downstream: ['dashboard_kpi'],
        fields: [
          { name: 'month', type: 'DATE', desc: '月份（YYYY-MM）', source: 'Wikimedia Pageviews API', required: true },
          { name: 'trend_type', type: 'VARCHAR(50)', desc: '趋势类型（public_interest/erp_internal_units_proxy/gmv/units）', source: '采集任务', required: true },
          { name: 'region', type: 'VARCHAR(50)', desc: '区域；公开兴趣代理为global', source: '采集任务', required: true },
          { name: 'category', type: 'VARCHAR(50)', desc: '品类；当前公开代理为Breast pump', source: '采集任务', required: true },
          { name: 'interest_index', type: 'DECIMAL(6,2)', desc: '公开兴趣指数，完整月峰值=100', source: 'Wikimedia Pageviews API', required: true },
          { name: 'pageviews', type: 'INT', desc: '页面月浏览量', source: 'Wikimedia Pageviews API', required: true },
          { name: 'is_partial_month', type: 'BOOLEAN', desc: '是否非完整月', source: '计算字段', required: true },
          { name: 'gmv_usd_m', type: 'DECIMAL(10,2)', desc: '月度GMV（百万美元），待授权后填写', source: 'Amazon/Vendor Central或ERP', required: false },
          { name: 'units_k', type: 'INT', desc: '销量（千件）；ERP当前仅为private/internal代理，待字段字典和展示审批后填写正式值', source: 'Amazon/Vendor Central或ERP', required: false },
          { name: 'asp_usd', type: 'DECIMAL(8,2)', desc: '平均售价（美元），待授权后填写', source: '计算字段', required: false },
          { name: 'mom_pct', type: 'DECIMAL(5,2)', desc: '环比增速 %', source: '计算字段', required: false },
          { name: 'yoy_pct', type: 'DECIMAL(5,2)', desc: '同比增速 %', source: '计算字段', required: false },
          { name: 'source_id', type: 'VARCHAR(20)', desc: '来源登记ID（ds-046/ds-047/ds-048/ds-049或授权来源ID）', source: 'source-registry', required: true },
        ],
      },
      {
        id: 't_pest', name: 'pest_analysis', desc: 'PEST宏观环境分析数据',
        updateFreq: '季度', upstream: [], downstream: ['market_size_global'],
        fields: [
          { name: 'dimension', type: 'VARCHAR(10)', desc: '维度（P政治/E经济/S社会/T技术）', source: '手工录入', required: true },
          { name: 'factor', type: 'VARCHAR(100)', desc: '具体因子名称', source: '手工录入', required: true },
          { name: 'country', type: 'VARCHAR(50)', desc: '影响国家/区域', source: '手工录入', required: true },
          { name: 'impact_level', type: 'INT', desc: '影响程度（1-5，5最高）', source: '专家评估', required: true },
          { name: 'impact_desc', type: 'TEXT', desc: '影响描述', source: '手工录入', required: true },
          { name: 'effective_date', type: 'DATE', desc: '生效日期', source: '官方文件', required: true },
          { name: 'source_url', type: 'VARCHAR(500)', desc: '政策原文链接', source: '官方网站', required: false },
        ],
      },
      {
        id: 't_porter', name: 'porter_five_forces', desc: '波特五力竞争强度分析',
        updateFreq: '半年', upstream: [], downstream: ['competitive_landscape'],
        fields: [
          { name: 'force', type: 'VARCHAR(50)', desc: '五力名称', source: '专家评估', required: true },
          { name: 'intensity', type: 'INT', desc: '竞争强度（1-5）', source: '专家评估', required: true },
          { name: 'assessment', type: 'TEXT', desc: '强度评估说明', source: '手工录入', required: true },
          { name: 'key_players', type: 'TEXT', desc: '关键参与方', source: '手工录入', required: false },
          { name: 'updated_at', type: 'TIMESTAMP', desc: '更新时间', source: '系统', required: true },
        ],
      },
      {
        id: 't_customs', name: 'customs_data', desc: '海关进出口数据（HS编码级）',
        updateFreq: '月度', upstream: ['各国海关'], downstream: ['market_trend_monthly'],
        fields: [
          { name: 'hs_code', type: 'VARCHAR(20)', desc: 'HS编码', source: '海关数据', required: true },
          { name: 'product_desc', type: 'VARCHAR(200)', desc: '产品描述', source: '海关', required: true },
          { name: 'import_country', type: 'VARCHAR(50)', desc: '进口国', source: '海关', required: true },
          { name: 'export_country', type: 'VARCHAR(50)', desc: '出口国', source: '海关', required: true },
          { name: 'value_usd', type: 'DECIMAL(12,2)', desc: '货值（美元）', source: '海关', required: true },
          { name: 'quantity', type: 'INT', desc: '数量（件/千克）', source: '海关', required: true },
          { name: 'duty_rate', type: 'DECIMAL(5,2)', desc: '关税率 %', source: '海关', required: true },
          { name: 'month', type: 'DATE', desc: '月份', source: '海关', required: true },
        ],
      },
      {
        id: 't_category', name: 'category_analysis', desc: '品类分析数据（吸奶器/文胸/配件等）',
        updateFreq: '月度', upstream: ['market_trend_monthly'], downstream: ['dashboard_kpi'],
        fields: [
          { name: 'category', type: 'VARCHAR(50)', desc: '品类名称', source: 'Amazon', required: true },
          { name: 'subcategory', type: 'VARCHAR(50)', desc: '子品类', source: 'Amazon', required: true },
          { name: 'brand', type: 'VARCHAR(50)', desc: '品牌', source: 'Amazon', required: true },
          { name: 'product_name', type: 'VARCHAR(200)', desc: '产品名称', source: 'Amazon', required: true },
          { name: 'bsr', type: 'INT', desc: 'Best Seller Rank', source: 'Amazon', required: true },
          { name: 'rating', type: 'DECIMAL(3,2)', desc: '评分', source: 'Amazon', required: true },
          { name: 'review_count', type: 'INT', desc: '评价数', source: 'Amazon', required: true },
          { name: 'price_usd', type: 'DECIMAL(8,2)', desc: '售价（美元）', source: 'Amazon', required: true },
          { name: 'snapshot_date', type: 'DATE', desc: '采集日期', source: '系统', required: true },
        ],
      },
    ],
  },
{
    id: 'comp', name: '竞争情报数据', icon: Target, color: '#ff9500', page: '/competition',
    desc: '看竞争模块所需全部数据，覆盖竞品产品、新品监测、区域竞争、价格、品牌份额',
    sourceIds: dataCatalogSourceIds,

    tables: [
      {
        id: 't_comp_product', name: 'competitor_products', desc: '竞品产品数据库（Amazon连接器待接入）',
        updateFreq: '半月复核', upstream: ['<span className="text-[#B5AFA8]">Amazon.com</span>'], downstream: ['new_product_tracker', 'price_analysis'],
        fields: [
          { name: 'product_id', type: 'VARCHAR(20)', desc: '产品唯一ID', source: '系统生成', required: true },
          { name: 'brand', type: 'VARCHAR(50)', desc: '品牌（Medela/Elvie/Willow等）', source: 'Amazon', required: true },
          { name: 'product_name', type: 'VARCHAR(200)', desc: '产品全称', source: 'Amazon', required: true },
          { name: 'category', type: 'VARCHAR(50)', desc: '品类', source: 'Amazon', required: true },
          { name: 'product_type', type: 'VARCHAR(100)', desc: '类型（穿戴式/双边/手动等）', source: 'Amazon', required: true },
          { name: 'price_usd', type: 'DECIMAL(8,2)', desc: '当前售价（美元）', source: 'Amazon', required: true },
          { name: 'rating', type: 'DECIMAL(3,2)', desc: 'Amazon评分', source: 'Amazon', required: true },
          { name: 'review_count', type: 'INT', desc: '评价数', source: 'Amazon', required: true },
          { name: 'suction_level', type: 'VARCHAR(50)', desc: '吸力等级', source: '产品规格', required: false },
          { name: 'battery_life', type: 'VARCHAR(50)', desc: '续航时间', source: '产品规格', required: false },
          { name: 'noise_level_db', type: 'INT', desc: '噪音水平（dB）', source: '产品规格', required: false },
          { name: 'weight_g', type: 'INT', desc: '重量（克）', source: '产品规格', required: false },
          { name: 'has_app', type: 'BOOLEAN', desc: '是否有APP', source: '产品规格', required: true },
          { name: 'fda_cleared', type: 'BOOLEAN', desc: 'FDA 510(k)认证', source: 'FDA数据库', required: true },
          { name: 'ce_certified', type: 'BOOLEAN', desc: 'CE认证', source: '产品规格', required: true },
          { name: 'highlight', type: 'TEXT', desc: '产品亮点', source: 'Amazon', required: false },
          { name: 'source_url', type: 'VARCHAR(500)', desc: 'Amazon产品链接', source: 'Amazon', required: true },
          { name: 'snapshot_date', type: 'DATE', desc: '采集日期', source: '系统', required: true },
        ],
      },
      {
        id: 't_new_product', name: 'new_product_tracker', desc: '新品上市追踪监测',
        updateFreq: '周', upstream: ['competitor_products'], downstream: ['dashboard_kpi'],
        fields: [
          { name: 'product_id', type: 'VARCHAR(20)', desc: '产品ID', source: 'competitor_products', required: true },
          { name: 'brand', type: 'VARCHAR(50)', desc: '品牌', source: 'competitor_products', required: true },
          { name: 'product_name', type: 'VARCHAR(200)', desc: '产品名称', source: '手工录入', required: true },
          { name: 'launch_date', type: 'DATE', desc: '上市日期', source: '新闻/官网', required: true },
          { name: 'launch_region', type: 'VARCHAR(100)', desc: '首发区域', source: '新闻/官网', required: true },
          { name: 'key_innovation', type: 'TEXT', desc: '核心技术创新点', source: '新闻/官网', required: true },
          { name: 'threat_level', type: 'VARCHAR(20)', desc: '威胁等级（高/中/低）', source: '专家评估', required: true },
          { name: 'response_strategy', type: 'TEXT', desc: '应对策略建议', source: '专家评估', required: false },
          { name: 'status', type: 'VARCHAR(20)', desc: '状态（在售/即将上市/已下架）', source: '手工录入', required: true },
        ],
      },
      {
        id: 't_region_comp', name: 'region_competitive_landscape', desc: '区域竞争格局数据',
        updateFreq: '季度', upstream: ['market_size_global'], downstream: ['dashboard_kpi'],
        fields: [
          { name: 'country', type: 'VARCHAR(50)', desc: '国家', source: 'Amazon+内部', required: true },
          { name: 'region', type: 'VARCHAR(50)', desc: '大洲区域', source: '系统', required: true },
          { name: 'brand', type: 'VARCHAR(50)', desc: '品牌', source: 'Amazon', required: true },
          { name: 'market_share_pct', type: 'DECIMAL(5,2)', desc: '市场份额 %', source: 'Amazon Brand Analytics', required: true },
          { name: 'bsr_avg', type: 'INT', desc: '平均BSR排名', source: 'Amazon', required: true },
          { name: 'price_position', type: 'VARCHAR(20)', desc: '价格定位（高端/中端/低端）', source: '计算字段', required: true },
          { name: 'distribution_channels', type: 'TEXT', desc: '销售渠道', source: '调研', required: false },
          { name: 'snapshot_date', type: 'DATE', desc: '采集日期', source: '系统', required: true },
        ],
      },
      {
        id: 't_price', name: 'price_analysis', desc: '价格分析数据（历史价格走势）',
        updateFreq: '周', upstream: ['competitor_products'], downstream: ['dashboard_kpi'],
        fields: [
          { name: 'product_id', type: 'VARCHAR(20)', desc: '产品ID', source: 'competitor_products', required: true },
          { name: 'price_usd', type: 'DECIMAL(8,2)', desc: '价格（美元）', source: 'Amazon', required: true },
          { name: 'promotion_type', type: 'VARCHAR(50)', desc: '促销类型（Prime Day/Black Friday/常规）', source: 'Amazon', required: false },
          { name: 'discount_pct', type: 'DECIMAL(5,2)', desc: '折扣率 %', source: '计算字段', required: false },
          { name: 'snapshot_date', type: 'DATE', desc: '采集日期', source: '系统', required: true },
        ],
      },
    ],
  },
{
    id: 'user', name: '用户研究数据', icon: Users, color: '#af52de', page: '/users',
    desc: '看用户模块所需全部数据，覆盖用户画像、社交声量、评论、消费者/渠道/店铺访谈',
    sourceIds: dataCatalogSourceIds,

    tables: [
      {
        id: 't_persona', name: 'user_personas', desc: '用户画像数据（6类核心人群）',
        updateFreq: '半年', upstream: ['consumer_interviews'], downstream: ['rfm_analysis'],
        fields: [
          { name: 'persona_id', type: 'VARCHAR(20)', desc: '画像ID', source: '系统', required: true },
          { name: 'persona_name', type: 'VARCHAR(50)', desc: '画像名称（孕期妈妈/新手妈妈等）', source: '手工录入', required: true },
          { name: 'age_range', type: 'VARCHAR(20)', desc: '年龄范围', source: '调研', required: true },
          { name: 'income_level', type: 'VARCHAR(50)', desc: '收入水平', source: '调研', required: true },
          { name: 'pct_of_userbase', type: 'DECIMAL(5,2)', desc: '占用户基数 %', source: 'CRM', required: true },
          { name: 'growth_rate', type: 'DECIMAL(5,2)', desc: '增速 %', source: 'CRM', required: true },
          { name: 'key_traits', type: 'TEXT', desc: '关键特征描述', source: '调研', required: true },
          { name: 'core_needs', type: 'TEXT', desc: '核心诉求', source: '调研', required: true },
          { name: 'pain_points', type: 'TEXT', desc: '痛点', source: '调研', required: true },
          { name: 'purchase_channels', type: 'TEXT', desc: '购买渠道偏好', source: '调研', required: true },
          { name: 'info_sources', type: 'TEXT', desc: '信息获取渠道', source: '调研', required: true },
          { name: 'avg_order_value', type: 'DECIMAL(8,2)', desc: '平均客单价（美元）', source: 'CRM', required: true },
          { name: 'color', type: 'VARCHAR(20)', desc: '画像标识色', source: '系统', required: true },
        ],
      },
      {
        id: 't_social', name: 'social_mention_data', desc: '社交声量监测数据',
        updateFreq: '日', upstream: ['社交媒体API'], downstream: ['dashboard_kpi'],
        fields: [
          { name: 'date', type: 'DATE', desc: '日期', source: '社交媒体API', required: true },
          { name: 'platform', type: 'VARCHAR(50)', desc: '平台（TikTok/IG/FB等）', source: 'API', required: true },
          { name: 'brand', type: 'VARCHAR(50)', desc: '被提及品牌', source: 'API', required: true },
          { name: 'mention_count', type: 'INT', desc: '提及次数', source: 'API', required: true },
          { name: 'sentiment_score', type: 'DECIMAL(4,2)', desc: '情感分（-1到+1）', source: 'NLP模型', required: true },
          { name: 'engagement_count', type: 'INT', desc: '互动数（点赞+评论+转发）', source: 'API', required: true },
          { name: 'reach_count', type: 'INT', desc: '触达人数', source: 'API', required: true },
        ],
      },
      {
        id: 't_comment', name: 'user_comments', desc: '用户评论明细数据',
        updateFreq: '日', upstream: ['Amazon API'], downstream: ['comment_analysis_ai'],
        fields: [
          { name: 'comment_id', type: 'VARCHAR(50)', desc: '评论唯一ID', source: 'Amazon', required: true },
          { name: 'product_id', type: 'VARCHAR(20)', desc: '产品ID', source: 'competitor_products', required: true },
          { name: 'brand', type: 'VARCHAR(50)', desc: '品牌', source: 'Amazon', required: true },
          { name: 'rating', type: 'INT', desc: '评分（1-5星）', source: 'Amazon', required: true },
          { name: 'review_text', type: 'TEXT', desc: '评论原文', source: 'Amazon', required: true },
          { name: 'review_date', type: 'DATE', desc: '评论日期', source: 'Amazon', required: true },
          { name: 'helpful_votes', type: 'INT', desc: ' helpful votes', source: 'Amazon', required: false },
          { name: 'verified_purchase', type: 'BOOLEAN', desc: '是否Verified Purchase', source: 'Amazon', required: true },
          { name: 'country', type: 'VARCHAR(50)', desc: '评论者国家', source: 'Amazon', required: false },
          { name: 'language', type: 'VARCHAR(20)', desc: '评论语言', source: 'NLP模型', required: true },
        ],
      },
      {
        id: 't_consumer_iv', name: 'consumer_interviews', desc: '消费者访谈记录',
        updateFreq: '季度', upstream: [], downstream: ['user_personas'],
        fields: [
          { name: 'interview_id', type: 'VARCHAR(20)', desc: '访谈ID', source: '系统', required: true },
          { name: 'persona_type', type: 'VARCHAR(50)', desc: '所属画像类型', source: '手工录入', required: true },
          { name: 'name', type: 'VARCHAR(100)', desc: '受访者化名', source: '手工录入', required: true },
          { name: 'age', type: 'INT', desc: '年龄', source: '访谈', required: true },
          { name: 'ethnicity', type: 'VARCHAR(50)', desc: '族裔', source: '访谈', required: false },
          { name: 'job', type: 'VARCHAR(100)', desc: '职业', source: '访谈', required: true },
          { name: 'hobbies', type: 'TEXT', desc: '爱好', source: '访谈', required: false },
          { name: 'baby_status', type: 'TEXT', desc: '育儿状态', source: '访谈', required: true },
          { name: 'current_product', type: 'TEXT', desc: '当前使用产品', source: '访谈', required: true },
          { name: 'usage_freq', type: 'TEXT', desc: '使用频率', source: '访谈', required: true },
          { name: 'usage_scenes', type: 'TEXT', desc: '使用场景', source: '访谈', required: true },
          { name: 'preferences', type: 'TEXT', desc: '产品偏好', source: '访谈', required: true },
          { name: 'positioning', type: 'TEXT', desc: '产品定位认知', source: '访谈', required: true },
          { name: 'needs', type: 'TEXT', desc: '需求', source: '访谈', required: true },
          { name: 'pain_points', type: 'TEXT', desc: '痛点', source: '访谈', required: true },
          { name: 'purchase_channels', type: 'TEXT', desc: '购买渠道', source: '访谈', required: true },
          { name: 'purchase_focus', type: 'TEXT', desc: '购买关注点', source: '访谈', required: true },
          { name: 'info_sources', type: 'TEXT', desc: '信息来源', source: '访谈', required: true },
          { name: 'family_situation', type: 'TEXT', desc: '家庭情况', source: '访谈', required: true },
          { name: 'life_focus', type: 'TEXT', desc: '生活重点', source: '访谈', required: true },
          { name: 'attention_areas', type: 'TEXT', desc: '关注领域', source: '访谈', required: true },
          { name: 'interview_date', type: 'DATE', desc: '访谈日期', source: '系统', required: true },
        ],
      },
      {
        id: 't_rfm', name: 'rfm_user_segments', desc: 'RFM用户价值分层数据',
        updateFreq: '月度', upstream: ['user_personas'], downstream: ['dashboard_kpi'],
        fields: [
          { name: 'user_id', type: 'VARCHAR(50)', desc: '用户ID（脱敏）', source: 'CRM', required: true },
          { name: 'segment', type: 'VARCHAR(50)', desc: '用户层级（重要价值/重要发展等）', source: 'RFM模型', required: true },
          { name: 'recency_days', type: 'INT', desc: '最近购买距今天数', source: 'CRM', required: true },
          { name: 'frequency', type: 'INT', desc: '购买频次', source: 'CRM', required: true },
          { name: 'monetary_usd', type: 'DECIMAL(8,2)', desc: '累计消费金额（美元）', source: 'CRM', required: true },
          { name: 'recommended_action', type: 'TEXT', desc: '推荐运营动作', source: 'RFM模型', required: true },
          { name: 'calc_date', type: 'DATE', desc: '计算日期', source: '系统', required: true },
        ],
      },
    ],
  },
{
    id: 'ind', name: '行业动态数据', icon: Shield, color: '#5856d6', page: '/industry',
    desc: '看行业模块所需全部数据，覆盖政策法规、供应链、IP专利、展会、宏观',
    sourceIds: dataCatalogSourceIds,
    tables: [
      {
        id: 't_policy', name: 'policy_regulations', desc: '政策法规数据库',
        updateFreq: '周', upstream: ['各国政府网站'], downstream: ['dashboard_kpi'],
        fields: [
          { name: 'policy_id', type: 'VARCHAR(20)', desc: '政策唯一ID', source: '系统', required: true },
          { name: 'country', type: 'VARCHAR(50)', desc: '国家', source: '政府网站', required: true },
          { name: 'regulator', type: 'VARCHAR(100)', desc: '监管机构', source: '政府网站', required: true },
          { name: 'title', type: 'VARCHAR(500)', desc: '政策标题', source: '政府网站', required: true },
          { name: 'effective_date', type: 'DATE', desc: '生效日期', source: '政府网站', required: true },
          { name: 'tag', type: 'VARCHAR(50)', desc: '标签（合规新规/标准更新/强制认证等）', source: '手工录入', required: true },
          { name: 'urgency', type: 'VARCHAR(20)', desc: '紧急程度（urgent/normal）', source: '评估', required: true },
          { name: 'full_text', type: 'TEXT', desc: '政策全文', source: '政府网站', required: false },
          { name: 'impact_assessment', type: 'TEXT', desc: '影响评估', source: '专家评估', required: false },
          { name: 'source_url', type: 'VARCHAR(500)', desc: '原文链接', source: '政府网站', required: true },
          { name: 'created_at', type: 'TIMESTAMP', desc: '入库时间', source: '系统', required: true },
        ],
      },
      {
        id: 't_supply', name: 'supply_chain_nodes', desc: '供应链节点数据',
        updateFreq: '季度', upstream: ['内部ERP'], downstream: ['dashboard_kpi'],
        fields: [
          { name: 'node_id', type: 'VARCHAR(20)', desc: '节点ID', source: 'ERP', required: true },
          { name: 'node_type', type: 'VARCHAR(50)', desc: '节点类型（工厂/仓库/分销中心）', source: 'ERP', required: true },
          { name: 'location', type: 'VARCHAR(200)', desc: '地理位置（城市, 国家）', source: 'ERP', required: true },
          { name: 'lat', type: 'DECIMAL(10,6)', desc: '纬度', source: '地图API', required: true },
          { name: 'lng', type: 'DECIMAL(10,6)', desc: '经度', source: '地图API', required: true },
          { name: 'capacity', type: 'TEXT', desc: '产能/仓储能力描述', source: 'ERP', required: false },
          { name: 'status', type: 'VARCHAR(20)', desc: '运营状态（正常/扩建/规划中）', source: 'ERP', required: true },
        ],
      },
      {
        id: 't_ip', name: 'ip_patents', desc: 'IP专利资产数据',
        updateFreq: '月度', upstream: ['WIPO/USPTO'], downstream: ['dashboard_kpi'],
        fields: [
          { name: 'patent_id', type: 'VARCHAR(50)', desc: '专利号', source: 'WIPO', required: true },
          { name: 'title', type: 'VARCHAR(500)', desc: '专利名称', source: 'WIPO', required: true },
          { name: 'assignee', type: 'VARCHAR(100)', desc: '专利权人', source: 'WIPO', required: true },
          { name: 'patent_type', type: 'VARCHAR(50)', desc: '类型（发明/实用新型/外观）', source: 'WIPO', required: true },
          { name: 'filing_date', type: 'DATE', desc: '申请日期', source: 'WIPO', required: true },
          { name: 'grant_date', type: 'DATE', desc: '授权日期', source: 'WIPO', required: false },
          { name: 'status', type: 'VARCHAR(50)', desc: '状态（授权/审查中/驳回）', source: 'WIPO', required: true },
          { name: 'country', type: 'VARCHAR(50)', desc: '申请国', source: 'WIPO', required: true },
          { name: 'ipc_class', type: 'VARCHAR(50)', desc: 'IPC分类号', source: 'WIPO', required: true },
          { name: 'abstract', type: 'TEXT', desc: '专利摘要', source: 'WIPO', required: true },
        ],
      },
      {
        id: 't_exhibition', name: 'trade_exhibitions', desc: '展会情报数据',
        updateFreq: '月度', upstream: ['展会官网'], downstream: ['dashboard_kpi'],
        fields: [
          { name: 'exhibition_id', type: 'VARCHAR(20)', desc: '展会ID', source: '系统', required: true },
          { name: 'name', type: 'VARCHAR(200)', desc: '展会全称', source: '展会官网', required: true },
          { name: 'city', type: 'VARCHAR(100)', desc: '举办城市', source: '展会官网', required: true },
          { name: 'country', type: 'VARCHAR(50)', desc: '举办国家', source: '展会官网', required: true },
          { name: 'start_date', type: 'DATE', desc: '开始日期', source: '展会官网', required: true },
          { name: 'end_date', type: 'DATE', desc: '结束日期', source: '展会官网', required: true },
          { name: 'category', type: 'VARCHAR(100)', desc: '展会类型（婴童/消费电子等）', source: '展会官网', required: true },
          { name: 'importance', type: 'VARCHAR(20)', desc: '重要程度（核心/关注/参考）', source: '评估', required: true },
          { name: 'booth_info', type: 'TEXT', desc: '展位信息', source: '内部', required: false },
          { name: 'key_findings', type: 'TEXT', desc: '关键发现', source: '调研', required: false },
        ],
      },
    ],
  },
{
    id: 'self', name: '品牌自研数据', icon: Eye, color: '#34c759', page: '/self',
    desc: '看自己模块所需全部数据，覆盖产品、定价、渠道、推广（营销4P）',
    sourceIds: dataCatalogSourceIds,
    tables: [
      {
        id: 't_own_product', name: 'momcozy_products', desc: 'Momcozy自有产品数据库',
        updateFreq: '月度', upstream: ['内部ERP'], downstream: ['product_analysis'],
        fields: [
          { name: 'sku', type: 'VARCHAR(20)', desc: 'SKU编码', source: 'ERP', required: true },
          { name: 'product_name', type: 'VARCHAR(200)', desc: '产品名称', source: 'ERP', required: true },
          { name: 'category', type: 'VARCHAR(50)', desc: '品类', source: 'ERP', required: true },
          { name: 'product_type', type: 'VARCHAR(100)', desc: '类型', source: 'ERP', required: true },
          { name: 'price_usd', type: 'DECIMAL(8,2)', desc: '官方售价（美元）', source: 'ERP', required: true },
          { name: 'cost_usd', type: 'DECIMAL(8,2)', desc: 'BOM成本（美元）', source: 'ERP', required: true },
          { name: 'margin_pct', type: 'DECIMAL(5,2)', desc: '毛利率 %', source: '计算字段', required: true },
          { name: 'launch_date', type: 'DATE', desc: '上市日期', source: 'ERP', required: true },
          { name: 'status', type: 'VARCHAR(20)', desc: '状态（在售/即将上市/退市）', source: 'ERP', required: true },
          { name: 'bcg_quadrant', type: 'VARCHAR(20)', desc: 'BCG象限（明星/现金牛/问题/瘦狗）', source: '计算字段', required: false },
          { name: 'innovation_desc', type: 'TEXT', desc: '创新点描述', source: '产品部', required: true },
        ],
      },
      {
        id: 't_price_strategy', name: 'pricing_strategy', desc: '定价策略数据',
        updateFreq: '周', upstream: ['momcozy_products', 'competitor_products'], downstream: ['dashboard_kpi'],
        fields: [
          { name: 'sku', type: 'VARCHAR(20)', desc: 'SKU编码', source: 'momcozy_products', required: true },
          { name: 'channel', type: 'VARCHAR(50)', desc: '渠道（Amazon/DTC/Target等）', source: 'ERP', required: true },
          { name: 'regular_price', type: 'DECIMAL(8,2)', desc: '日常售价', source: 'ERP', required: true },
          { name: 'promo_price', type: 'DECIMAL(8,2)', desc: '促销价', source: 'ERP', required: false },
          { name: 'promo_type', type: 'VARCHAR(50)', desc: '促销类型', source: 'ERP', required: false },
          { name: 'asp_usd', type: 'DECIMAL(8,2)', desc: '实际ASP（美元）', source: '计算字段', required: true },
          { name: 'asp_vs_comp', type: 'DECIMAL(5,2)', desc: 'vs竞品ASP差异 %', source: '计算字段', required: false },
          { name: 'week_ending', type: 'DATE', desc: '统计周截止日', source: '系统', required: true },
        ],
      },
      {
        id: 't_channel', name: 'channel_performance', desc: '渠道表现数据',
        updateFreq: '月度', upstream: ['ERP'], downstream: ['dashboard_kpi'],
        fields: [
          { name: 'channel', type: 'VARCHAR(50)', desc: '渠道名称', source: 'ERP', required: true },
          { name: 'region', type: 'VARCHAR(50)', desc: '区域', source: 'ERP', required: true },
          { name: 'revenue_pct', type: 'DECIMAL(5,2)', desc: '营收占比 %', source: 'ERP', required: true },
          { name: 'growth_pct', type: 'DECIMAL(5,2)', desc: '增长率 %', source: '计算字段', required: true },
          { name: 'margin_pct', type: 'DECIMAL(5,2)', desc: '毛利率 %', source: 'ERP', required: true },
          { name: 'control_score', type: 'INT', desc: '品牌控制力（1-100）', source: '评估', required: true },
          { name: 'month', type: 'DATE', desc: '月份', source: '系统', required: true },
        ],
      },
      {
        id: 't_promo', name: 'promotion_campaigns', desc: '推广活动数据',
        updateFreq: '活动后', upstream: ['各平台API'], downstream: ['dashboard_kpi'],
        fields: [
          { name: 'campaign_id', type: 'VARCHAR(20)', desc: '活动ID', source: '系统', required: true },
          { name: 'campaign_name', type: 'VARCHAR(200)', desc: '活动名称', source: '市场部', required: true },
          { name: 'type', type: 'VARCHAR(50)', desc: '活动类型（Prime Day/Brand Day等）', source: '市场部', required: true },
          { name: 'channel', type: 'VARCHAR(50)', desc: '渠道', source: '市场部', required: true },
          { name: 'start_date', type: 'DATE', desc: '开始日期', source: '市场部', required: true },
          { name: 'end_date', type: 'DATE', desc: '结束日期', source: '市场部', required: true },
          { name: 'discount_pct', type: 'DECIMAL(5,2)', desc: '折扣率 %', source: '市场部', required: true },
          { name: 'featured_sku', type: 'TEXT', desc: '主推SKU', source: '市场部', required: true },
          { name: 'budget_usd', type: 'DECIMAL(10,2)', desc: '预算（美元）', source: '市场部', required: true },
          { name: 'roas', type: 'DECIMAL(5,2)', desc: 'ROAS（广告回报率）', source: '计算字段', required: false },
          { name: 'impressions', type: 'INT', desc: '曝光量', source: 'API', required: false },
          { name: 'leads', type: 'INT', desc: '线索数', source: 'API', required: false },
        ],
      },
    ],
  },
{
    id: 'ai', name: 'AI辅助数据', icon: Sparkles, color: '#af52de', page: '/ai-assistant',
    desc: 'AI助手模块所需全部数据，覆盖dataset manifest、model run manifest、评论/VOC样本清单、eval队列、设计/图库run、资产hash、成本队列、商用审核门禁、报告队列、评论分析、设计助手、知识库、数据评论',
    sourceIds: dataCatalogSourceIds,
    tables: [
      {
        id: 't_ai_dataset_manifest', name: 'ai_dataset_manifest', desc: 'AI与报告输入数据集治理清单；Batch4仅为readiness gate',
        updateFreq: '每次采集', upstream: ['tmp/exports/ai-report-governance-batch4-20260625/ai_dataset_manifest.csv'], downstream: ['ai_model_run_manifest', 'report_generation_queue'],
        fields: [
          { name: 'dataset_id', type: 'VARCHAR(80)', desc: '数据集标识，如comments_voc_dataset或erp_context_dataset', source: 'Batch4治理脚本', required: true },
          { name: 'source_ids', type: 'TEXT', desc: 'source registry IDs，如ds-021/ds-030/ds-047', source: 'source-registry', required: true },
          { name: 'data_scope', type: 'TEXT', desc: '数据范围和输出契约；不包含原始评论正文或客户数据', source: 'Batch4治理脚本', required: true },
          { name: 'required_artifacts', type: 'TEXT', desc: '升级前所需证据包、hash、评估报告或审批记录', source: '证据门禁', required: true },
          { name: 'current_status', type: 'VARCHAR(120)', desc: 'blocked/metadata_only/gated_internal_proxy_available', source: 'Batch4治理脚本', required: true },
          { name: 'evidence_grade', type: 'VARCHAR(40)', desc: '当前L2-fixture-or-dry-run或L3只读上下文', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false，不可作为AI结论或报告正文事实', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_ai_model_run_manifest', name: 'ai_model_run_manifest', desc: 'AI模型运行审计清单；当前未接入真实模型调用日志',
        updateFreq: '每次模型运行', upstream: ['ai_dataset_manifest', 'tmp/exports/ai-report-governance-batch4-20260625/ai_model_run_manifest.csv'], downstream: ['ai_human_review_gate', 'comment_analysis_ai', 'design_assistant_output'],
        fields: [
          { name: 'model_run_id', type: 'VARCHAR(100)', desc: '模型运行契约标识，如comment_nlp_run', source: 'Batch4治理脚本', required: true },
          { name: 'surface', type: 'VARCHAR(160)', desc: '页面或能力面', source: 'Batch4治理脚本', required: true },
          { name: 'input_dataset_id', type: 'TEXT', desc: '输入数据集标识，不保存原始评论或prompt正文', source: 'ai_dataset_manifest', required: true },
          { name: 'model_name_status', type: 'VARCHAR(100)', desc: '模型版本状态，当前blocked_missing_model_version', source: '模型审计待接入', required: true },
          { name: 'prompt_version_status', type: 'VARCHAR(100)', desc: '提示词版本状态，当前blocked_missing_prompt_version', source: '模型审计待接入', required: true },
          { name: 'run_trace_status', type: 'VARCHAR(120)', desc: 'requestId和trace状态，当前blocked_missing_request_id_and_trace', source: '服务端审计待接入', required: true },
          { name: 'human_review_required', type: 'BOOLEAN', desc: '是否必须人工复核，当前true', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false，模型输出不能作为事实', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_ai_human_review_gate', name: 'ai_human_review_gate', desc: 'AI输出与报告结论人工复核门禁',
        updateFreq: '每次发布前', upstream: ['ai_model_run_manifest', 'tmp/exports/ai-report-governance-batch4-20260625/ai_human_review_gate.csv'], downstream: ['report_generation_queue', 'dashboard_kpi'],
        fields: [
          { name: 'review_gate_id', type: 'VARCHAR(100)', desc: '复核门禁标识', source: 'Batch4治理脚本', required: true },
          { name: 'surface', type: 'VARCHAR(180)', desc: '复核覆盖页面或报告类型', source: 'Batch4治理脚本', required: true },
          { name: 'required_review_roles', type: 'TEXT', desc: '所需复核角色', source: '证据门禁', required: true },
          { name: 'minimum_sample_contract', type: 'TEXT', desc: '最小抽样或一致率要求', source: '证据门禁', required: true },
          { name: 'approval_state', type: 'VARCHAR(60)', desc: '当前not_approved', source: '人工复核', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false，未审批不可进入报告正文或CSV导出', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_report_generation_queue', name: 'report_generation_queue', desc: 'AI辅助报告生成队列；当前只登记待补证报告类型',
        updateFreq: '半月/按需', upstream: ['ai_dataset_manifest', 'ai_human_review_gate', 'tmp/exports/ai-report-governance-batch4-20260625/report_generation_queue.csv'], downstream: ['ReportsPage', 'ReportPreview'],
        fields: [
          { name: 'report_id', type: 'VARCHAR(100)', desc: '报告队列标识，如internal_ops_monthly', source: 'Batch4治理脚本', required: true },
          { name: 'report_type', type: 'VARCHAR(120)', desc: '报告类型', source: '报告治理', required: true },
          { name: 'source_ids', type: 'TEXT', desc: '上游source IDs', source: 'source-registry', required: true },
          { name: 'input_datasets', type: 'TEXT', desc: '输入数据集清单', source: 'ai_dataset_manifest', required: true },
          { name: 'output_artifact_status', type: 'VARCHAR(120)', desc: '输出产物状态，当前均为blocked', source: 'Batch4治理脚本', required: true },
          { name: 'can_generate', type: 'BOOLEAN', desc: '当前false，不生成正式报告正文', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false，不展示为报告事实', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_ai_erp_context_bridge', name: 'ai_erp_context_bridge', desc: 'ERP内部上下文到AI/报告的桥接规则；禁止越权推断',
        updateFreq: '月度', upstream: ['ds-035', 'ds-047', 'ds-049', 'ds-050', 'ds-051', 'tmp/exports/ai-report-governance-batch4-20260625/ai_erp_context_bridge.csv'], downstream: ['ai_dataset_manifest', 'report_generation_queue', 'design_assistant_output'],
        fields: [
          { name: 'bridge_id', type: 'VARCHAR(100)', desc: '桥接规则标识', source: 'Batch4治理脚本', required: true },
          { name: 'ai_surface', type: 'VARCHAR(180)', desc: 'AI或报告使用面', source: 'Batch4治理脚本', required: true },
          { name: 'erp_source_ids', type: 'TEXT', desc: 'ERP source IDs', source: 'source-registry', required: true },
          { name: 'allowed_use', type: 'TEXT', desc: '允许用途：采集优先级、brief约束或内部numerator上下文', source: '证据门禁', required: true },
          { name: 'forbidden_use', type: 'TEXT', desc: '禁止用途：用户情绪、评论数量、TAM/SAM/SOM、竞品份额或库存事实', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false，桥接上下文不可单独作为事实', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_ai_review_sample_manifest', name: 'ai_review_sample_manifest', desc: '评论/VOC/YouTube/Web样本清单；Batch5仅登记采集合同与缺口',
        updateFreq: '每次样本采集', upstream: ['ds-021', 'ds-023', 'ds-030', 'ds-031', 'ds-032', 'ds-033', 'tmp/exports/ai-review-governance-batch5-20260625/ai_review_sample_manifest.csv'], downstream: ['ai_review_eval_queue', 'ai_review_human_queue', 'comment_analysis_ai'],
        fields: [
          { name: 'sample_manifest_id', type: 'VARCHAR(120)', desc: '样本清单标识，如review_analysis_voc_model_sample', source: 'Batch5治理脚本', required: true },
          { name: 'surface', type: 'VARCHAR(80)', desc: '页面或能力面，如CommentData/YoutubeReview/FlavorMap', source: 'Batch5治理脚本', required: true },
          { name: 'source_ids', type: 'TEXT', desc: 'source registry IDs，如ds-021/ds-031/ds-032', source: 'source-registry', required: true },
          { name: 'sample_scope', type: 'TEXT', desc: '样本范围与采集合同；不包含原始评论正文', source: 'Batch5治理脚本', required: true },
          { name: 'sampling_window_status', type: 'VARCHAR(120)', desc: '样本窗口状态，当前均为blocked或待授权', source: '证据门禁', required: true },
          { name: 'raw_text_policy', type: 'VARCHAR(120)', desc: '原文策略，当前hash/summary/metadata优先，不导出正文', source: '隐私治理', required: true },
          { name: 'pii_policy', type: 'VARCHAR(120)', desc: 'PII处理策略，需脱敏或聚合后才能展示', source: '隐私治理', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false，不可作为评论或VOC事实', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_ai_review_eval_queue', name: 'ai_review_eval_queue', desc: '评论/VOC模型或规则评估队列；当前未接入真实模型评估报告',
        updateFreq: '每次模型/规则评估', upstream: ['ai_review_sample_manifest', 'tmp/exports/ai-review-governance-batch5-20260625/ai_review_eval_queue.csv'], downstream: ['ai_review_human_queue', 'ai_human_review_gate'],
        fields: [
          { name: 'eval_queue_id', type: 'VARCHAR(120)', desc: '评估队列标识', source: 'Batch5治理脚本', required: true },
          { name: 'sample_manifest_id', type: 'VARCHAR(120)', desc: '对应样本清单', source: 'ai_review_sample_manifest', required: true },
          { name: 'metric_contract', type: 'TEXT', desc: '评估指标契约，如准确率、召回率、一致率或合规覆盖率', source: '证据门禁', required: true },
          { name: 'model_version_status', type: 'VARCHAR(120)', desc: '模型或规则版本状态，当前blocked_missing_model_version', source: '模型审计待接入', required: true },
          { name: 'golden_set_status', type: 'VARCHAR(120)', desc: '人工标注或golden set状态，当前缺失', source: '人工复核', required: true },
          { name: 'request_trace_status', type: 'VARCHAR(120)', desc: 'requestId/jobId状态，当前缺失', source: '服务端审计待接入', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false，评估未完成前模型输出不可展示为事实', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_ai_review_human_queue', name: 'ai_review_human_queue', desc: '评论/VOC/YouTube/Web人工复核队列；发布前必须通过',
        updateFreq: '每次发布前', upstream: ['ai_review_eval_queue', 'tmp/exports/ai-review-governance-batch5-20260625/ai_review_human_queue.csv'], downstream: ['ai_review_publish_gate', 'ai_human_review_gate'],
        fields: [
          { name: 'review_task_id', type: 'VARCHAR(120)', desc: '人工复核任务ID', source: 'Batch5治理脚本', required: true },
          { name: 'eval_queue_id', type: 'VARCHAR(120)', desc: '对应评估队列ID', source: 'ai_review_eval_queue', required: true },
          { name: 'required_roles', type: 'TEXT', desc: '所需复核角色，如法务、用户研究、数据治理', source: '证据门禁', required: true },
          { name: 'minimum_review_contract', type: 'TEXT', desc: '最小复核样本或审批例外要求', source: '人工复核', required: true },
          { name: 'approval_state', type: 'VARCHAR(60)', desc: '当前not_approved', source: '人工复核', required: true },
          { name: 'can_publish', type: 'BOOLEAN', desc: '当前false，未审批不可发布', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false，未审批不可作为事实', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_ai_review_publish_gate', name: 'ai_review_publish_gate', desc: '评论/VOC/YouTube/Web发布门禁；阻断未补证的统计、趋势、评分和报告结论',
        updateFreq: '每次发布/导出前', upstream: ['ai_review_human_queue', 'tmp/exports/ai-review-governance-batch5-20260625/ai_review_publish_gate.csv'], downstream: ['ReviewAnalysis', 'CommentData', 'YoutubeReview', 'WebReview', 'FlavorMap', 'FlavorReport', 'ReportsPage'],
        fields: [
          { name: 'publish_gate_id', type: 'VARCHAR(120)', desc: '发布门禁ID', source: 'Batch5治理脚本', required: true },
          { name: 'surface', type: 'VARCHAR(80)', desc: '页面或能力面', source: 'Batch5治理脚本', required: true },
          { name: 'blocked_claim_types', type: 'TEXT', desc: '阻断的claim类型，如评论量、情绪百分比、趋势预测或站点评分', source: '证据门禁', required: true },
          { name: 'allowed_display', type: 'TEXT', desc: '允许展示内容：采集合同、缺失证据和阻断原因', source: '证据门禁', required: true },
          { name: 'forbidden_display', type: 'TEXT', desc: '禁止展示内容：真实KPI、平台事实、模型结论或报告建议', source: '证据门禁', required: true },
          { name: 'can_export', type: 'BOOLEAN', desc: '当前false，证据补齐前不得进入CSV或报告导出', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_ai_design_run_manifest', name: 'ai_design_run_manifest', desc: '设计助手/AI图库生成请求治理清单；Batch6不含真实requestId或模型调用日志',
        updateFreq: '每次生成请求', upstream: ['ds-026', 'ds-029', 'ds-047', 'ds-049', 'tmp/exports/ai-design-governance-batch6-20260625/ai_design_run_manifest.csv'], downstream: ['ai_design_asset_hash_manifest', 'ai_design_cost_queue', 'design_assistant_output'],
        fields: [
          { name: 'design_run_id', type: 'VARCHAR(120)', desc: '生成运行契约标识，如design_assistant_generation_proxy', source: 'Batch6治理脚本', required: true },
          { name: 'surface', type: 'VARCHAR(120)', desc: '页面或能力面，如DesignAssistant/AIGallery', source: 'Batch6治理脚本', required: true },
          { name: 'source_ids', type: 'TEXT', desc: 'source registry IDs，如ds-026/ds-029/ds-047/ds-049', source: 'source-registry', required: true },
          { name: 'request_id_status', type: 'VARCHAR(120)', desc: 'requestId状态，当前blocked_missing_server_request_id', source: '服务端代理待接入', required: true },
          { name: 'model_version_status', type: 'VARCHAR(120)', desc: '模型版本状态，当前缺provider模型记录', source: '模型审计待接入', required: true },
          { name: 'prompt_version_status', type: 'VARCHAR(120)', desc: '提示词版本或hash状态，不保存提示词正文', source: '提示词治理', required: true },
          { name: 'parameter_hash_status', type: 'VARCHAR(120)', desc: '生成参数hash状态', source: '服务端审计待接入', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false，不可作为真实生成历史或成本事实', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_ai_design_asset_hash_manifest', name: 'ai_design_asset_hash_manifest', desc: '设计/图库资产hash与来源治理清单；不保存生成图片二进制',
        updateFreq: '每次素材入库', upstream: ['ai_design_run_manifest', 'tmp/exports/ai-design-governance-batch6-20260625/ai_design_asset_hash_manifest.csv'], downstream: ['ai_design_commercial_review_gate', 'ai_gallery'],
        fields: [
          { name: 'asset_manifest_id', type: 'VARCHAR(120)', desc: '资产清单ID，如gallery_local_asset_origin', source: 'Batch6治理脚本', required: true },
          { name: 'design_run_id', type: 'VARCHAR(120)', desc: '对应生成或入库run', source: 'ai_design_run_manifest', required: true },
          { name: 'asset_hash_status', type: 'VARCHAR(120)', desc: '最终资产hash状态，当前缺失', source: '资产治理', required: true },
          { name: 'source_asset_hash_status', type: 'VARCHAR(120)', desc: '源图/参考图hash状态，当前缺失或不适用', source: '资产治理', required: true },
          { name: 'prompt_hash_status', type: 'VARCHAR(120)', desc: 'prompt hash状态，不保存prompt正文', source: '提示词治理', required: true },
          { name: 'storage_policy', type: 'VARCHAR(120)', desc: '存储策略：只保存hash、路径或review metadata，不导出二进制', source: '隐私治理', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false，未完成hash和来源记录前不可作为素材事实', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_ai_design_cost_queue', name: 'ai_design_cost_queue', desc: '设计/图库生成成本审计队列；当前不含provider invoice或真实成本',
        updateFreq: '每次成本结算', upstream: ['ai_design_run_manifest', 'tmp/exports/ai-design-governance-batch6-20260625/ai_design_cost_queue.csv'], downstream: ['ai_design_commercial_review_gate', 'ReportsPage'],
        fields: [
          { name: 'cost_queue_id', type: 'VARCHAR(120)', desc: '成本队列ID', source: 'Batch6治理脚本', required: true },
          { name: 'design_run_id', type: 'VARCHAR(120)', desc: '对应生成run', source: 'ai_design_run_manifest', required: true },
          { name: 'provider_invoice_status', type: 'VARCHAR(120)', desc: '供应商账单状态，当前缺失', source: '财务审计待接入', required: true },
          { name: 'unit_cost_status', type: 'VARCHAR(120)', desc: '单位成本状态，当前缺失', source: '成本治理', required: true },
          { name: 'currency_policy_status', type: 'VARCHAR(120)', desc: '币种和汇率口径状态', source: '成本治理', required: true },
          { name: 'cost_charged', type: 'BOOLEAN', desc: '当前false，未发生或未登记真实扣费', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false，不能展示成本节省或ROI', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_ai_design_commercial_review_gate', name: 'ai_design_commercial_review_gate', desc: '设计/图库商用审核门禁；阻断未审批素材发布和导出',
        updateFreq: '每次素材发布前', upstream: ['ai_design_asset_hash_manifest', 'ai_design_cost_queue', 'tmp/exports/ai-design-governance-batch6-20260625/ai_design_commercial_review_gate.csv'], downstream: ['DesignAssistant', 'AIGallery', 'ReportsPage'],
        fields: [
          { name: 'review_gate_id', type: 'VARCHAR(120)', desc: '商用审核门禁ID', source: 'Batch6治理脚本', required: true },
          { name: 'asset_manifest_id', type: 'VARCHAR(120)', desc: '对应资产清单ID', source: 'ai_design_asset_hash_manifest', required: true },
          { name: 'required_roles', type: 'TEXT', desc: '所需审核角色，如品牌、法务、创意负责人', source: '证据门禁', required: true },
          { name: 'brand_review_status', type: 'VARCHAR(120)', desc: '品牌审核状态，当前缺失', source: '人工复核', required: true },
          { name: 'rights_status', type: 'VARCHAR(120)', desc: '版权/来源权利状态，当前缺失', source: '法务复核', required: true },
          { name: 'can_use_commercially', type: 'BOOLEAN', desc: '当前false，未审批不可商用', source: '证据门禁', required: true },
          { name: 'can_publish', type: 'BOOLEAN', desc: '当前false，未审批不可发布', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_comment_ai', name: 'comment_analysis_ai', desc: 'AI评论分析结果',
        updateFreq: '日', upstream: ['user_comments'], downstream: ['dashboard_kpi'],
        fields: [
          { name: 'analysis_id', type: 'VARCHAR(20)', desc: '分析ID', source: '系统', required: true },
          { name: 'product_id', type: 'VARCHAR(20)', desc: '产品ID', source: 'user_comments', required: true },
          { name: 'aspect', type: 'VARCHAR(100)', desc: '分析维度（吸力/静音/续航等）', source: 'NLP模型', required: true },
          { name: 'sentiment', type: 'VARCHAR(20)', desc: '情感（positive/negative/neutral）', source: 'NLP模型', required: true },
          { name: 'mention_pct', type: 'DECIMAL(5,2)', desc: '提及占比 %', source: 'NLP模型', required: true },
          { name: 'sample_quotes', type: 'TEXT', desc: '典型引用', source: 'NLP模型', required: false },
          { name: 'run_date', type: 'DATE', desc: '分析运行日期', source: '系统', required: true },
        ],
      },
      {
        id: 't_design_ai', name: 'design_assistant_output', desc: 'AI设计助手输出记录',
        updateFreq: '每次', upstream: [], downstream: [],
        fields: [
          { name: 'output_id', type: 'VARCHAR(20)', desc: '输出ID', source: '系统', required: true },
          { name: 'prompt', type: 'TEXT', desc: '用户输入Prompt', source: '用户', required: true },
          { name: 'output_image_url', type: 'VARCHAR(500)', desc: '生成图片URL', source: 'AI模型', required: true },
          { name: 'model_used', type: 'VARCHAR(50)', desc: '使用的AI模型', source: '系统', required: true },
          { name: 'created_at', type: 'TIMESTAMP', desc: '生成时间', source: '系统', required: true },
        ],
      },
      {
        id: 't_kb', name: 'knowledge_base', desc: 'AI知识库内容',
        updateFreq: '实时', upstream: [], downstream: ['ai-assistant'],
        fields: [
          { name: 'doc_id', type: 'VARCHAR(20)', desc: '文档ID', source: '系统', required: true },
          { name: 'title', type: 'VARCHAR(500)', desc: '文档标题', source: '手工录入', required: true },
          { name: 'category', type: 'VARCHAR(100)', desc: '分类', source: '手工录入', required: true },
          { name: 'content', type: 'LONGTEXT', desc: '文档内容', source: '手工录入', required: true },
          { name: 'embedding_vector', type: 'TEXT', desc: '向量嵌入', source: 'AI模型', required: false },
          { name: 'created_at', type: 'TIMESTAMP', desc: '创建时间', source: '系统', required: true },
        ],
      },
      {
        id: 't_web_review', name: 'web_review_scraped', desc: '网页评论爬取数据',
        updateFreq: '周', upstream: ['各网站'], downstream: ['comment_analysis_ai'],
        fields: [
          { name: 'review_id', type: 'VARCHAR(50)', desc: '评论ID', source: '爬虫', required: true },
          { name: 'source_site', type: 'VARCHAR(200)', desc: '来源网站', source: '爬虫', required: true },
          { name: 'product_name', type: 'VARCHAR(200)', desc: '产品名称', source: '爬虫', required: true },
          { name: 'rating', type: 'INT', desc: '评分', source: '爬虫', required: true },
          { name: 'review_text', type: 'TEXT', desc: '评论内容', source: '爬虫', required: true },
          { name: 'review_date', type: 'DATE', desc: '评论日期', source: '爬虫', required: true },
          { name: 'author', type: 'VARCHAR(100)', desc: '评论者', source: '爬虫', required: false },
          { name: 'scraped_at', type: 'TIMESTAMP', desc: '爬取时间', source: '系统', required: true },
        ],
      },
    ],
  }
];
