import { HardDrive } from 'lucide-react';

import type { DataModule } from './model';

const dataCatalogSourceIds = ['ds-027'];

export const erpDataModules: DataModule[] = [
{
    id: 'erp', name: 'ERP内部经营数据', icon: HardDrive, color: '#0A84FF', page: '/data',
    desc: 'ERP/BI内部经营数据治理层，沉淀source artifact、SKU维表、月度事实、目标达成、库存快照、字段字典、品类映射和Batch19 release review；已放行项按private/internal proxy展示',
    sourceIds: dataCatalogSourceIds,
    tables: [
      {
        id: 't_erp_artifact', name: 'erp_source_artifacts', desc: 'ERP导出与只读采集证据总账',
        updateFreq: '每次采集', upstream: ['ERP导出', 'ERP UI只读采集', 'BI只读报告'], downstream: ['source_registry', 'erp_sales_monthly_fact', 'erp_retail_channel_monthly_fact'],
        fields: [
          { name: 'source_id', type: 'VARCHAR(20)', desc: 'source registry ID，如ds-047/ds-048/ds-049/ds-050/ds-051', source: 'source-registry', required: true },
          { name: 'source_path', type: 'VARCHAR(300)', desc: 'ERP/BI菜单路径，不保存含session的完整URL', source: 'ERP只读采集', required: true },
          { name: 'artifact_path', type: 'VARCHAR(500)', desc: '本地证据路径，默认位于tmp/exports或tmp/audits', source: '采集任务', required: true },
          { name: 'sha256', type: 'VARCHAR(64)', desc: '原始文件或CSV哈希', source: '采集任务', required: false },
          { name: 'row_count', type: 'INT', desc: '采集行数或导出行数', source: '采集任务', required: false },
          { name: 'captured_at', type: 'TIMESTAMP', desc: '采集时间', source: '系统', required: true },
          { name: 'privacy_level', type: 'VARCHAR(30)', desc: 'public/private/internal/sensitive/secret', source: 'source-registry', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '是否可作为页面事实展示；Batch19放行项为true，未放行ERP来源仍保持false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_sku', name: 'erp_product_sku_dim', desc: 'ERP SKU与产品hash维表；Batch2仅沉淀pseudonymized字段',
        updateFreq: '月度', upstream: ['ds-049', 'tmp/exports/erp-derived-batch2-20260625/erp_product_sku_dim.csv'], downstream: ['momcozy_products', 'category_analysis', 'comment_analysis_ai'],
        fields: [
          { name: 'sku_hash', type: 'VARCHAR(64)', desc: '带命名空间的SKU哈希；不展示原始SKU', source: 'Batch2派生脚本', required: true },
          { name: 'product_name_hash', type: 'VARCHAR(64)', desc: '产品名称哈希；不展示原始产品名', source: 'Batch2派生脚本', required: true },
          { name: 'category_proxy', type: 'VARCHAR(120)', desc: '关键词品类代理，如breast_pump_keyword_proxy', source: 'Batch2派生脚本', required: true },
          { name: 'mapped_page_category', type: 'VARCHAR(120)', desc: '映射到的页面路径，如/market/mtl', source: 'erp_category_mapping', required: true },
          { name: 'raw_row_count', type: 'INT', desc: '该hash在零售导出中的行覆盖', source: 'ds-049', required: true },
          { name: 'total_visible_proxy_units', type: 'INT', desc: '可见月度列代理量合计；不是GMV或市场销量', source: 'ds-049', required: true },
          { name: 'has_customer_field', type: 'BOOLEAN', desc: '原始导出是否含客户字段；字段值不入库展示', source: 'Batch2隐私检查', required: true },
          { name: 'has_operator_field', type: 'BOOLEAN', desc: '原始导出是否含运营字段；字段值不入库展示', source: 'Batch2隐私检查', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前true，Batch19放行为internal proxy；不代表公开SKU事实', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_sales_monthly', name: 'erp_sales_monthly_fact', desc: 'ERP销售统计月度内部代理事实表',
        updateFreq: '月度', upstream: ['ds-047', 'private/internal proxy artifact: tmp/exports/erp-derived-batch2-20260625/erp_sales_monthly_fact.csv'], downstream: ['market_trend_monthly', 'category_analysis', 'channel_performance', 'dashboard_kpi'],
        fields: [
          { name: 'month', type: 'DATE', desc: '月份', source: 'ERP销售统计导出', required: true },
          { name: 'fact_table', type: 'VARCHAR(80)', desc: '事实表标识，固定为erp_sales_monthly_fact', source: 'Batch2派生脚本', required: true },
          { name: 'category_proxy', type: 'VARCHAR(120)', desc: 'all_products或breast_pump_keyword_proxy', source: 'Batch2派生脚本', required: true },
          { name: 'proxy_units', type: 'INT', desc: '销量样式字段的内部代理值，待字段字典确认', source: 'ds-047', required: true },
          { name: 'index_peak_100', type: 'DECIMAL(8,2)', desc: '导出窗口峰值归一指数', source: 'Batch2派生脚本', required: false },
          { name: 'mom_pct', type: 'DECIMAL(8,2)', desc: '环比代理变化；不是外部市场增长率', source: 'Batch2派生脚本', required: false },
          { name: 'matched_data_rows', type: 'INT', desc: '参与该代理计算的原始行数', source: 'ds-047', required: true },
          { name: 'source_id', type: 'VARCHAR(20)', desc: 'ds-047或授权快照ID', source: 'source-registry', required: true },
          { name: 'evidence_grade', type: 'VARCHAR(40)', desc: '证据等级', source: 'source-registry', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前true，Batch19放行为internal proxy；不代表GMV或市场份额', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_after_sales_monthly', name: 'erp_after_sales_monthly_fact', desc: 'ERP售后销量月度内部代理事实表',
        updateFreq: '月度', upstream: ['ds-048', 'private/internal proxy artifact: tmp/exports/erp-derived-batch2-20260625/erp_after_sales_monthly_fact.csv'], downstream: ['comment_analysis_ai', 'category_analysis', 'market_trend_monthly'],
        fields: [
          { name: 'month', type: 'DATE', desc: '月份', source: 'ERP售后销量统计导出', required: true },
          { name: 'fact_table', type: 'VARCHAR(80)', desc: '事实表标识，固定为erp_after_sales_monthly_fact', source: 'Batch2派生脚本', required: true },
          { name: 'category_proxy', type: 'VARCHAR(120)', desc: 'all_products或breast_pump_keyword_proxy', source: 'Batch2派生脚本', required: true },
          { name: 'proxy_units', type: 'INT', desc: '售后销量样式字段内部代理值', source: 'ds-048', required: true },
          { name: 'index_peak_100', type: 'DECIMAL(8,2)', desc: '导出窗口峰值归一指数', source: 'Batch2派生脚本', required: false },
          { name: 'mom_pct', type: 'DECIMAL(8,2)', desc: '环比代理变化；不是售后率', source: 'Batch2派生脚本', required: false },
          { name: 'matched_data_rows', type: 'INT', desc: '参与该代理计算的原始行数', source: 'ds-048', required: true },
          { name: 'source_id', type: 'VARCHAR(20)', desc: 'ds-048或授权快照ID', source: 'source-registry', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前true，Batch19放行为internal proxy；不代表售后率', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_retail_channel_monthly', name: 'erp_retail_channel_monthly_fact', desc: 'ERP零售与渠道月度内部代理事实表',
        updateFreq: '月度', upstream: ['ds-049', 'tmp/exports/erp-derived-batch2-20260625/erp_retail_channel_monthly_fact.csv'], downstream: ['channel_performance', 'store_interviews', 'region_competitive_landscape'],
        fields: [
          { name: 'month', type: 'DATE', desc: '月份', source: 'ERP零售与渠道UI分页采集', required: true },
          { name: 'fact_table', type: 'VARCHAR(80)', desc: '事实表标识，固定为erp_retail_channel_monthly_fact', source: 'Batch2派生脚本', required: true },
          { name: 'category_proxy', type: 'VARCHAR(120)', desc: 'all_products或breast_pump_keyword_proxy', source: 'Batch2派生脚本', required: true },
          { name: 'proxy_units', type: 'INT', desc: '可见月度销量列代理值', source: 'ds-049', required: true },
          { name: 'index_peak_100', type: 'DECIMAL(8,2)', desc: '导出窗口峰值归一指数', source: 'Batch2派生脚本', required: false },
          { name: 'mom_pct', type: 'DECIMAL(8,2)', desc: '环比代理变化；不是外部渠道增速', source: 'Batch2派生脚本', required: false },
          { name: 'matched_data_rows', type: 'INT', desc: '参与该代理计算的原始行数', source: 'ds-049', required: true },
          { name: 'source_id', type: 'VARCHAR(20)', desc: 'ds-049或授权快照ID', source: 'source-registry', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前true，Batch19放行为internal proxy；小计差异保留为口径说明', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_channel_growth', name: 'erp_channel_growth_snapshot', desc: 'ERP/BI全渠道增长只读聚合快照；Batch3仅沉淀YTD numerator',
        updateFreq: '月度', upstream: ['ds-050', 'private/internal proxy artifact: tmp/exports/erp-derived-batch3-20260625/erp_channel_growth_snapshot.csv'], downstream: ['channel_performance', 'self_insight', 'region_competitive_landscape'],
        fields: [
          { name: 'period', type: 'VARCHAR(40)', desc: '统计期间，当前为2026-ytd-readonly-observed', source: 'Batch3派生脚本', required: true },
          { name: 'snapshot_type', type: 'VARCHAR(80)', desc: '快照类型，固定为all_channel_growth_snapshot', source: 'Batch3派生脚本', required: true },
          { name: 'actual_sales_cny', type: 'DECIMAL(14,2)', desc: '只读聚合实际销售额人民币；Batch19 private/internal proxy', source: 'ds-050', required: false },
          { name: 'sales_growth_pct', type: 'DECIMAL(8,2)', desc: '只读聚合销售增长率；非市场增长率', source: 'ds-050', required: false },
          { name: 'actual_sales_usd', type: 'DECIMAL(14,2)', desc: '只读聚合实际销售额美元；非公开市场规模', source: 'ds-050', required: false },
          { name: 'actual_units', type: 'INT', desc: '只读聚合销量；非市场销量或份额分母', source: 'ds-050', required: false },
          { name: 'source_id', type: 'VARCHAR(20)', desc: 'ds-050或授权快照ID', source: 'source-registry', required: true },
          { name: 'evidence_grade', type: 'VARCHAR(40)', desc: 'L3-production-read-only', source: 'source-registry', required: true },
          { name: 'privacy_level', type: 'VARCHAR(30)', desc: 'private/internal', source: 'source-registry', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前true，仅作为内部numerator proxy；不可作为公开事实或TAM/SAM/SOM', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_channel_target', name: 'erp_channel_target_attainment', desc: 'ERP/BI全渠道目标达成事实表',
        updateFreq: '月度', upstream: ['ds-050', 'ds-051', 'private/internal proxy artifact: tmp/exports/erp-derived-batch3-20260625/erp_channel_target_attainment.csv'], downstream: ['channel_performance', 'ReportsPage', 'dashboard_kpi'],
        fields: [
          { name: 'period', type: 'VARCHAR(40)', desc: '统计期间，当前为2026-ytd-readonly-observed', source: 'Batch3派生脚本', required: true },
          { name: 'snapshot_type', type: 'VARCHAR(80)', desc: '快照类型，固定为all_channel_target_attainment', source: 'Batch3派生脚本', required: true },
          { name: 'sales_attainment_pct', type: 'DECIMAL(8,2)', desc: '销售额达成率；只读聚合', source: 'ds-051', required: false },
          { name: 'units_attainment_pct', type: 'DECIMAL(8,2)', desc: '销量达成率；只读聚合', source: 'ds-051', required: false },
          { name: 'actual_sales_cny', type: 'DECIMAL(14,2)', desc: '实际销售额人民币；Batch19 private/internal proxy', source: 'ds-051或授权导出', required: false },
          { name: 'target_sales_cny', type: 'DECIMAL(14,2)', desc: '目标销售额人民币；Batch19 private/internal proxy', source: 'ds-051或授权导出', required: false },
          { name: 'actual_sales_usd', type: 'DECIMAL(14,2)', desc: '实际销售额美元；非公开市场规模', source: 'ds-051或授权导出', required: false },
          { name: 'actual_units', type: 'INT', desc: '实际销量；非市场销量或份额分母', source: 'ds-051或授权导出', required: false },
          { name: 'target_units', type: 'INT', desc: '目标销量；Batch19 private/internal proxy', source: 'ds-051或授权导出', required: false },
          { name: 'source_id', type: 'VARCHAR(20)', desc: 'ds-050/ds-051或授权快照ID', source: 'source-registry', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前true，仅作为内部目标达成proxy；不可作为公开事实或TAM/SAM/SOM', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_channel_customer_dim', name: 'erp_channel_customer_dim', desc: 'ERP零售与渠道客户/目的仓/运营hash维表；Batch3仅沉淀pseudonymized字段',
        updateFreq: '月度', upstream: ['ds-049', 'private/internal proxy artifact: tmp/exports/erp-derived-batch3-20260625/erp_channel_customer_dim.csv'], downstream: ['channel_performance', 'channel_interviews', 'store_interviews', 'region_competitive_landscape'],
        fields: [
          { name: 'channel_customer_hash', type: 'VARCHAR(64)', desc: '客户名称hash；不展示原始客户名', source: 'Batch3派生脚本', required: true },
          { name: 'destination_warehouse_hash', type: 'VARCHAR(64)', desc: '目的仓hash；不展示原始仓库名', source: 'Batch3派生脚本', required: true },
          { name: 'operator_hash', type: 'VARCHAR(64)', desc: '运营字段hash；不展示原始人员或账号', source: 'Batch3派生脚本', required: false },
          { name: 'raw_row_count', type: 'INT', desc: '该hash组合在零售导出中的行覆盖', source: 'ds-049', required: true },
          { name: 'sku_hash_count', type: 'INT', desc: '该hash组合覆盖的SKU hash数量', source: 'ds-049', required: true },
          { name: 'visible_proxy_units', type: 'INT', desc: '可见月度列代理量合计；不是GMV、份额或市场销量', source: 'ds-049', required: true },
          { name: 'category_proxy_top', type: 'VARCHAR(120)', desc: '该hash组合的主要关键词品类代理', source: 'Batch3派生脚本', required: true },
          { name: 'source_id', type: 'VARCHAR(20)', desc: 'ds-049或授权快照ID', source: 'source-registry', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前true，Batch19放行为internal proxy；不展示客户排行或原始标识', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_inventory_snapshot', name: 'erp_inventory_snapshot', desc: 'ERP库存快照表',
        updateFreq: '日/周', upstream: ['ds-035', 'blocked readiness artifact: tmp/exports/erp-derived-batch3-20260625/erp_inventory_snapshot_readiness.csv'], downstream: ['supply_chain_nodes', 'dashboard_kpi'],
        fields: [
          { name: 'snapshot_date', type: 'DATE', desc: '快照日期；当前blocked_missing_inventory_export', source: 'ERP库存导出待授权', required: true },
          { name: 'warehouse_hash', type: 'VARCHAR(64)', desc: '仓库hash；当前未采集库存导出', source: 'ERP库存导出待授权', required: true },
          { name: 'sku_hash', type: 'VARCHAR(64)', desc: 'SKU hash；当前未采集库存导出', source: 'ERP库存导出待授权', required: true },
          { name: 'on_hand_units', type: 'INT', desc: '在库库存；当前仅登记字段readiness，不含数值', source: 'ds-035待授权导出', required: true },
          { name: 'available_units', type: 'INT', desc: '可用库存；当前仅登记字段readiness，不含数值', source: 'ds-035待授权导出', required: true },
          { name: 'reserved_units', type: 'INT', desc: '预占库存；当前仅登记字段readiness，不含数值', source: 'ds-035待授权导出', required: false },
          { name: 'frozen_units', type: 'INT', desc: '冻结库存；当前仅登记字段readiness，不含数值', source: 'ds-035待授权导出', required: false },
          { name: 'in_transit_units', type: 'INT', desc: '在途库存；当前仅登记字段readiness，不含数值', source: 'ds-035待授权导出', required: false },
          { name: 'defective_units', type: 'INT', desc: '不良品库存；当前仅登记字段readiness，不含数值', source: 'ds-035待授权导出', required: false },
          { name: 'readiness_status', type: 'VARCHAR(80)', desc: '当前blocked_missing_inventory_export', source: 'Batch3派生脚本', required: true },
          { name: 'inventory_policy_version', type: 'VARCHAR(80)', desc: '库存口径版本；当前blocked_missing_inventory_export', source: 'Batch3派生脚本', required: true },
          { name: 'source_id', type: 'VARCHAR(20)', desc: '授权库存快照ID；当前仅为blocked readiness登记，can_display_as_fact=false', source: 'source-registry', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false，未授权导出前不得展示库存事实', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_field_dictionary', name: 'erp_field_dictionary', desc: 'ERP字段字典与单位口径表',
        updateFreq: '字段变更时', upstream: ['ds-047', 'ds-048', 'ds-049', 'ds-050', 'ds-051', 'tmp/exports/erp-governance-batch7-20260625/erp_field_dictionary_readiness.csv'], downstream: ['全部ERP事实表', 'erp_field_owner_approval_packet', 'erp_display_approval_gate'],
        fields: [
          { name: 'source_id', type: 'VARCHAR(20)', desc: '来源ID', source: 'source-registry', required: true },
          { name: 'table_name', type: 'VARCHAR(120)', desc: 'ERP源表或页面', source: 'ERP字段字典', required: true },
          { name: 'field_name', type: 'VARCHAR(120)', desc: '原始字段名', source: 'ERP字段字典', required: true },
          { name: 'business_meaning', type: 'TEXT', desc: '业务含义', source: '人工复核', required: true },
          { name: 'unit', type: 'VARCHAR(40)', desc: '单位，如件/金额/百分比', source: '人工复核', required: true },
          { name: 'currency', type: 'VARCHAR(20)', desc: '币种，仅金额字段填写', source: '人工复核', required: false },
          { name: 'hidden_column_behavior', type: 'TEXT', desc: '隐藏列、小计、周边界等行为说明', source: '人工复核', required: false },
          { name: 'review_status', type: 'VARCHAR(80)', desc: '当前needs-data-owner-review', source: 'Batch7治理脚本', required: true },
          { name: 'dictionary_status', type: 'VARCHAR(120)', desc: '当前blocked_missing_authorized_field_dictionary', source: 'Batch7治理脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false，字段字典未审批前不可展示事实', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_category_mapping', name: 'erp_category_mapping', desc: 'ERP产品到页面品类的治理映射表；Batch2为关键词代理',
        updateFreq: '月度', upstream: ['erp_product_sku_dim', 'tmp/exports/erp-derived-batch2-20260625/erp_category_mapping.csv'], downstream: ['erp_category_review_queue', 'market_trend_monthly', 'category_analysis', 'momcozy_products'],
        fields: [
          { name: 'category_proxy', type: 'VARCHAR(120)', desc: '关键词代理品类', source: 'Batch2派生脚本', required: true },
          { name: 'source_keyword_rule', type: 'VARCHAR(160)', desc: '关键词匹配规则版本', source: 'Batch2派生脚本', required: true },
          { name: 'mapped_page_category', type: 'VARCHAR(120)', desc: '映射到的页面路径', source: 'Batch2派生脚本', required: true },
          { name: 'sku_hash_count', type: 'INT', desc: '该代理下SKU hash数量', source: 'erp_product_sku_dim', required: true },
          { name: 'raw_row_count', type: 'INT', desc: '该代理覆盖的原始行数', source: 'ds-049', required: true },
          { name: 'visible_proxy_units', type: 'INT', desc: '可见月度代理量合计；不是市场销量', source: 'ds-049', required: true },
          { name: 'confidence', type: 'VARCHAR(20)', desc: 'low/medium/high；Batch2默认不超过medium', source: '映射任务', required: true },
          { name: 'review_status', type: 'VARCHAR(40)', desc: 'needs-review/approved/rejected', source: '品类管理人工复核', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前true，Batch19放行为关键词internal proxy；不作为外部品类事实', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_category_review_queue', name: 'erp_category_review_queue', desc: 'ERP关键词品类代理人工复核队列；Batch7仅生成待审任务',
        updateFreq: '月度/品类规则变更时', upstream: ['erp_category_mapping', 'tmp/exports/erp-governance-batch7-20260625/erp_category_review_queue.csv'], downstream: ['erp_category_owner_approval_packet', 'erp_display_approval_gate', 'category_analysis', 'momcozy_products'],
        fields: [
          { name: 'review_task_id', type: 'VARCHAR(160)', desc: '品类复核任务ID', source: 'Batch7治理脚本', required: true },
          { name: 'category_proxy', type: 'VARCHAR(120)', desc: '关键词代理品类', source: 'erp_category_mapping', required: true },
          { name: 'mapped_page_category', type: 'VARCHAR(120)', desc: '对应页面', source: 'erp_category_mapping', required: true },
          { name: 'priority', type: 'VARCHAR(20)', desc: '复核优先级，P0/P1', source: 'Batch7治理脚本', required: true },
          { name: 'reviewer_role', type: 'TEXT', desc: '所需复核角色', source: '证据门禁', required: true },
          { name: 'approval_status', type: 'VARCHAR(60)', desc: '当前not_approved', source: '人工复核', required: true },
          { name: 'acceptance_criteria', type: 'TEXT', desc: '通过标准：taxonomy规则、抽样SKU hash、未映射处理和展示范围', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_subtotal_reconciliation_queue', name: 'erp_subtotal_reconciliation_queue', desc: 'ERP小计、可见月度列、周边界或隐藏列复核队列',
        updateFreq: '每次ERP导出/字段字典变更', upstream: ['ds-047', 'ds-048', 'ds-049', 'tmp/exports/erp-governance-batch7-20260625/erp_subtotal_reconciliation_queue.csv'], downstream: ['erp_subtotal_owner_explanation_packet', 'erp_display_approval_gate', 'market_trend_monthly', 'erp_retail_channel_monthly_fact'],
        fields: [
          { name: 'reconciliation_id', type: 'VARCHAR(160)', desc: '复核项ID', source: 'Batch7治理脚本', required: true },
          { name: 'source_id', type: 'VARCHAR(20)', desc: 'ERP来源ID', source: 'source-registry', required: true },
          { name: 'affected_table', type: 'VARCHAR(120)', desc: '受影响治理表', source: 'Batch7治理脚本', required: true },
          { name: 'observed_delta_units', type: 'INT', desc: '已观察到的小计差异代理量；仅用于复核，不展示为事实', source: 'Batch7治理脚本', required: true },
          { name: 'reconciliation_status', type: 'VARCHAR(120)', desc: '复核状态', source: 'Batch7治理脚本', required: true },
          { name: 'next_evidence', type: 'TEXT', desc: '提升证据所需材料', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_display_approval_gate', name: 'erp_display_approval_gate', desc: 'ERP内部经营数据页面展示与CSV导出审批门禁',
        updateFreq: '发布/导出前', upstream: ['erp_field_dictionary', 'erp_category_review_queue', 'erp_subtotal_reconciliation_queue', 'tmp/exports/erp-governance-batch7-20260625/erp_display_approval_gate.csv'], downstream: ['erp_display_approval_record_template', 'erp_owner_approval_backlog', 'MarketPage', 'CategoryAnalysis', 'SelfInsight', 'ReportsPage', 'CSV exports'],
        fields: [
          { name: 'approval_gate_id', type: 'VARCHAR(160)', desc: '展示审批门禁ID', source: 'Batch7治理脚本', required: true },
          { name: 'table_name', type: 'VARCHAR(120)', desc: '受控表名', source: 'Batch7治理脚本', required: true },
          { name: 'surface', type: 'VARCHAR(200)', desc: '使用页面或能力面', source: 'Batch7治理脚本', required: true },
          { name: 'required_reviews', type: 'TEXT', desc: '所需审批：字段字典、品类/隐私/业务owner', source: '证据门禁', required: true },
          { name: 'approval_status', type: 'VARCHAR(60)', desc: '当前not_approved', source: '人工审批', required: true },
          { name: 'allowed_display', type: 'TEXT', desc: '允许展示的gate元数据', source: '证据门禁', required: true },
          { name: 'forbidden_display', type: 'TEXT', desc: '禁止展示的经营事实或敏感标识', source: '证据门禁', required: true },
          { name: 'can_export', type: 'BOOLEAN', desc: '当前false，未审批不可进入正式CSV导出', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_field_owner_approval_packet', name: 'erp_field_owner_approval_packet', desc: 'ERP字段字典owner审批包；Batch8仅生成待填写审批包',
        updateFreq: '字段变更/发布前', upstream: ['erp_field_dictionary', 'tmp/exports/erp-owner-approval-batch8-20260625/erp_field_owner_approval_packet.csv'], downstream: ['erp_owner_approval_backlog', 'erp_display_approval_record_template'],
        fields: [
          { name: 'approval_packet_id', type: 'VARCHAR(180)', desc: '字段owner审批包ID', source: 'Batch8审批脚本', required: true },
          { name: 'source_id', type: 'VARCHAR(20)', desc: 'ERP来源ID', source: 'source-registry', required: true },
          { name: 'table_name', type: 'VARCHAR(120)', desc: '受控ERP表', source: 'Batch7字段字典readiness', required: true },
          { name: 'owner_role', type: 'TEXT', desc: '需审批的业务owner角色', source: '证据门禁', required: true },
          { name: 'field_count', type: 'INT', desc: '该source/table下待审批字段数量', source: 'Batch8审批脚本', required: true },
          { name: 'editable_decision_fields', type: 'TEXT', desc: 'owner需填写的审批字段', source: '证据门禁', required: true },
          { name: 'approval_status', type: 'VARCHAR(80)', desc: '当前pending_owner_record', source: 'Batch8审批脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false，未审批前不可升级事实展示', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_category_owner_approval_packet', name: 'erp_category_owner_approval_packet', desc: 'ERP品类taxonomy owner审批包；Batch8仅生成待填写审批包',
        updateFreq: '月度/品类规则变更时', upstream: ['erp_category_review_queue', 'tmp/exports/erp-owner-approval-batch8-20260625/erp_category_owner_approval_packet.csv'], downstream: ['erp_owner_approval_backlog', 'erp_display_approval_record_template', 'category_analysis'],
        fields: [
          { name: 'approval_packet_id', type: 'VARCHAR(180)', desc: '品类owner审批包ID', source: 'Batch8审批脚本', required: true },
          { name: 'category_proxy', type: 'VARCHAR(120)', desc: '关键词代理品类', source: 'Batch7品类复核队列', required: true },
          { name: 'mapped_page_category', type: 'VARCHAR(120)', desc: '映射页面', source: 'Batch7品类复核队列', required: true },
          { name: 'required_decision', type: 'TEXT', desc: 'approve_or_reject_taxonomy_rule_and_unmapped_handling', source: '证据门禁', required: true },
          { name: 'editable_decision_fields', type: 'TEXT', desc: 'taxonomy rule、抽样SKU hash复核、展示范围等待填字段', source: '证据门禁', required: true },
          { name: 'approval_status', type: 'VARCHAR(80)', desc: '当前pending_owner_record', source: 'Batch8审批脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_subtotal_owner_explanation_packet', name: 'erp_subtotal_owner_explanation_packet', desc: 'ERP小计/隐藏列/周边界解释审批包；Batch8仅生成待填写审批包',
        updateFreq: '每次ERP导出/字段字典变更', upstream: ['erp_subtotal_reconciliation_queue', 'tmp/exports/erp-owner-approval-batch8-20260625/erp_subtotal_owner_explanation_packet.csv'], downstream: ['erp_owner_approval_backlog', 'erp_display_approval_record_template', 'market_trend_monthly'],
        fields: [
          { name: 'approval_packet_id', type: 'VARCHAR(180)', desc: '小计解释审批包ID', source: 'Batch8审批脚本', required: true },
          { name: 'reconciliation_id', type: 'VARCHAR(160)', desc: 'Batch7小计复核项ID', source: 'Batch7小计队列', required: true },
          { name: 'source_id', type: 'VARCHAR(20)', desc: 'ERP来源ID', source: 'source-registry', required: true },
          { name: 'observed_delta_units', type: 'INT', desc: '已观察小计差异代理量，仅用于审批说明，不展示事实', source: 'Batch7治理脚本', required: true },
          { name: 'editable_decision_fields', type: 'TEXT', desc: '官方小计公式、隐藏列行为、周边界、审批决定等待填字段', source: '证据门禁', required: true },
          { name: 'approval_status', type: 'VARCHAR(80)', desc: '当前pending_owner_record', source: 'Batch8审批脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_display_approval_record_template', name: 'erp_display_approval_record_template', desc: 'ERP表到页面/CSV导出展示审批记录模板；Batch8未应用真实审批',
        updateFreq: '发布/导出前', upstream: ['erp_display_approval_gate', 'tmp/exports/erp-owner-approval-batch8-20260625/erp_display_approval_record_template.csv'], downstream: ['erp_owner_approval_backlog', 'market_trend_monthly', 'dashboard_kpi', 'CSV exports'],
        fields: [
          { name: 'approval_record_id', type: 'VARCHAR(180)', desc: '展示审批记录ID', source: 'Batch8审批脚本', required: true },
          { name: 'table_name', type: 'VARCHAR(120)', desc: '受控表名', source: 'Batch7展示门禁', required: true },
          { name: 'surface', type: 'VARCHAR(200)', desc: '页面或能力面', source: 'Batch7展示门禁', required: true },
          { name: 'approval_decision', type: 'VARCHAR(80)', desc: '当前pending', source: 'Batch8审批模板', required: true },
          { name: 'approver_name_hash', type: 'VARCHAR(64)', desc: '审批人hash；当前为空，未写真实个人信息', source: '人工审批待填', required: false },
          { name: 'approval_record_uri', type: 'TEXT', desc: '审批记录URI；当前为空', source: '人工审批待填', required: false },
          { name: 'can_export', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_approval_backlog', name: 'erp_owner_approval_backlog', desc: 'ERP字段、品类、小计、展示审批统一backlog；Batch8仅为待办总账',
        updateFreq: '每次审批包生成/审批记录变更', upstream: ['erp_field_owner_approval_packet', 'erp_category_owner_approval_packet', 'erp_subtotal_owner_explanation_packet', 'erp_display_approval_record_template', 'tmp/exports/erp-owner-approval-batch8-20260625/erp_owner_approval_backlog.csv'], downstream: ['erp_owner_approval_record_input_template', 'erp_owner_approval_validation_result', 'data_governance', 'release_gate', 'market_trend_monthly', 'dashboard_kpi'],
        fields: [
          { name: 'approval_item_id', type: 'VARCHAR(180)', desc: '审批backlog项ID', source: 'Batch8审批脚本', required: true },
          { name: 'approval_lane', type: 'VARCHAR(120)', desc: '审批lane：字段/品类/小计/展示', source: 'Batch8审批脚本', required: true },
          { name: 'owner_role', type: 'TEXT', desc: '需处理角色', source: '证据门禁', required: true },
          { name: 'priority', type: 'VARCHAR(20)', desc: '优先级', source: 'Batch8审批脚本', required: true },
          { name: 'current_status', type: 'VARCHAR(120)', desc: '当前pending或missing owner record', source: 'Batch8审批脚本', required: true },
          { name: 'required_evidence', type: 'TEXT', desc: '升级证据所需材料', source: '证据门禁', required: true },
          { name: 'editable_packet', type: 'VARCHAR(160)', desc: 'owner应填写的审批包文件', source: 'Batch8审批脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false；全部backlog闭合前不得升级事实展示', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_approval_intake_contract', name: 'erp_owner_approval_intake_contract', desc: 'ERP owner approval intake 合同；定义必填字段、decision vocab 和 fail-closed 规则',
        updateFreq: '审批流程变更时', upstream: ['erp_owner_approval_backlog', 'tmp/exports/erp-owner-approval-intake-batch9-20260626/erp_owner_approval_intake_contract.csv'], downstream: ['erp_owner_approval_record_input_template', 'erp_owner_approval_required_evidence_matrix', 'erp_owner_approval_validation_result'],
        fields: [
          { name: 'approval_lane', type: 'VARCHAR(120)', desc: '字段、品类、小计或展示审批lane', source: 'Batch9 intake脚本', required: true },
          { name: 'required_record_key', type: 'VARCHAR(80)', desc: '审批记录主键，当前为approval_item_id', source: 'Batch9 intake脚本', required: true },
          { name: 'required_fields', type: 'TEXT', desc: '真实审批记录必须包含的字段集合', source: '证据门禁', required: true },
          { name: 'decision_vocab', type: 'TEXT', desc: '允许的审批结论：approved/denied/needs_revision', source: '证据门禁', required: true },
          { name: 'promotion_rule', type: 'TEXT', desc: '升级所需规则；当前仍需manual release review', source: '证据门禁', required: true },
          { name: 'fail_closed_rule', type: 'TEXT', desc: '缺失或不合法审批记录一律保持blocked', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_approval_validation_result', name: 'erp_owner_approval_validation_result', desc: 'ERP owner approval intake 校验结果；Batch9默认无真实审批记录输入',
        updateFreq: '每次审批记录回填/校验', upstream: ['erp_owner_approval_backlog', 'erp_owner_approval_intake_contract', 'tmp/exports/erp-owner-approval-intake-batch9-20260626/erp_owner_approval_validation_result.csv'], downstream: ['erp_owner_approval_release_gate'],
        fields: [
          { name: 'validation_id', type: 'VARCHAR(220)', desc: '审批记录校验ID', source: 'Batch9 intake脚本', required: true },
          { name: 'approval_item_id', type: 'VARCHAR(180)', desc: '对应Batch8 backlog项', source: 'erp_owner_approval_backlog', required: true },
          { name: 'approval_record_present', type: 'BOOLEAN', desc: '审批记录是否存在；Batch19放行链路对应记录已存在', source: 'Batch9 intake脚本', required: true },
          { name: 'validation_status', type: 'VARCHAR(120)', desc: 'passed_owner_record_validation 或 blocked_missing_or_invalid_owner_record', source: 'Batch9 intake脚本', required: true },
          { name: 'validation_messages', type: 'TEXT', desc: '阻断原因或校验说明', source: '证据门禁', required: true },
          { name: 'can_promote', type: 'BOOLEAN', desc: '当前false，脚本不自动升级事实展示', source: '证据门禁', required: true },
          { name: 'can_display_as_fact_decision', type: 'BOOLEAN', desc: '当前false', source: '审批记录待填', required: true },
        ],
      },
      {
        id: 't_erp_owner_approval_release_gate', name: 'erp_owner_approval_release_gate', desc: 'ERP owner approval release gate；所有校验通过后仍需manual release review',
        updateFreq: '每次审批校验后', upstream: ['erp_owner_approval_validation_result', 'tmp/exports/erp-owner-approval-intake-batch9-20260626/erp_owner_approval_release_gate.csv'], downstream: ['erp_owner_approval_submission_readiness', 'erp_owner_approval_promotion_manifest', 'market_trend_monthly', 'dashboard_kpi', 'CSV exports'],
        fields: [
          { name: 'release_gate_id', type: 'VARCHAR(180)', desc: '表级发布门禁ID', source: 'Batch9 intake脚本', required: true },
          { name: 'table_name', type: 'VARCHAR(120)', desc: '受控表名', source: 'Batch8展示审批模板', required: true },
          { name: 'relevant_validation_rows', type: 'INT', desc: '关联校验项数量', source: 'Batch9 intake脚本', required: true },
          { name: 'passed_validation_rows', type: 'INT', desc: '通过校验项数量；Batch19放行链路已有通过项', source: 'Batch9 intake脚本', required: true },
          { name: 'release_status', type: 'VARCHAR(120)', desc: 'ready_for_manual_release_review 或 blocked_missing_valid_owner_records', source: 'Batch9 intake脚本', required: true },
          { name: 'required_next_step', type: 'TEXT', desc: '下一步：已放行项进入Batch19 swap queue；未放行项继续收集合法owner审批记录', source: '证据门禁', required: true },
          { name: 'can_export', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_approval_promotion_manifest', name: 'erp_owner_approval_promotion_manifest', desc: 'ERP事实展示/导出升级候选清单；Batch9当前0行',
        updateFreq: 'manual release review后', upstream: ['erp_owner_approval_release_gate', 'tmp/exports/erp-owner-approval-intake-batch9-20260626/erp_owner_approval_promotion_manifest.csv'], downstream: ['release_gate', 'market_trend_monthly', 'dashboard_kpi', 'CSV exports'],
        fields: [
          { name: 'promotion_candidate_id', type: 'VARCHAR(220)', desc: '升级候选ID；当前无候选', source: 'Batch9 intake脚本', required: true },
          { name: 'approval_item_id', type: 'VARCHAR(180)', desc: '来源审批项ID', source: 'Batch9 intake脚本', required: true },
          { name: 'promotion_status', type: 'VARCHAR(120)', desc: '当前无候选；未来也需manual_release_review_required', source: '证据门禁', required: true },
          { name: 'can_export', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
          { name: 'blocking_reason', type: 'TEXT', desc: '当前missing-valid-owner-approval-records或manual-release-review-required', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_approval_owner_packet_index', name: 'erp_owner_approval_owner_packet_index', desc: 'ERP owner审批包索引；Batch10按lane汇总待填owner records',
        updateFreq: '每次审批模板生成', upstream: ['erp_owner_approval_backlog', 'erp_owner_approval_intake_contract', 'tmp/exports/erp-owner-approval-record-template-batch10-20260626/erp_owner_approval_owner_packet_index.csv'], downstream: ['erp_owner_approval_record_input_template'],
        fields: [
          { name: 'approval_lane', type: 'VARCHAR(120)', desc: '字段、品类、小计或展示审批lane', source: 'Batch10模板脚本', required: true },
          { name: 'editable_packet', type: 'VARCHAR(160)', desc: '对应Batch8待填写审批包', source: 'erp_owner_approval_backlog', required: true },
          { name: 'owner_role', type: 'TEXT', desc: '需填写审批记录的owner角色', source: '证据门禁', required: true },
          { name: 'backlog_items', type: 'INT', desc: '该lane下backlog项数量', source: 'Batch10模板脚本', required: true },
          { name: 'required_fields', type: 'TEXT', desc: 'Batch9 validator要求字段', source: 'erp_owner_approval_intake_contract', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false；索引不代表审批通过', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_approval_record_input_template', name: 'erp_owner_approval_record_input_template', desc: 'ERP owner approval records回填模板；23行预填approval_item_id，审批字段等待真实owner填写',
        updateFreq: '每次审批模板生成/owner回填前', upstream: ['erp_owner_approval_backlog', 'erp_owner_approval_intake_contract', 'tmp/exports/erp-owner-approval-record-template-batch10-20260626/erp_owner_approval_record_input_template.csv'], downstream: ['erp_owner_submission_schema_audit', 'erp_owner_submission_redaction_audit', 'erp_owner_approval_preflight_result', 'erp_owner_approval_validation_result'],
        fields: [
          { name: 'approval_item_id', type: 'VARCHAR(180)', desc: 'Batch8 backlog审批项ID', source: 'erp_owner_approval_backlog', required: true },
          { name: 'approval_decision', type: 'VARCHAR(40)', desc: '待填：approved/denied/needs_revision；当前为空', source: 'owner待填', required: true },
          { name: 'approver_name_hash', type: 'VARCHAR(64)', desc: '待填审批人hash；禁止写真实姓名', source: 'owner待填', required: true },
          { name: 'approval_record_uri', type: 'TEXT', desc: '待填可审计审批记录URI', source: 'owner待填', required: true },
          { name: 'forbidden_display_confirmed', type: 'BOOLEAN', desc: '默认false，需owner明确确认', source: '证据门禁', required: true },
          { name: 'can_export_decision', type: 'BOOLEAN', desc: '默认false', source: '证据门禁', required: true },
          { name: 'can_display_as_fact_decision', type: 'BOOLEAN', desc: '默认false', source: '证据门禁', required: true },
          { name: 'next_validator_command', type: 'TEXT', desc: '回填后运行Batch9 validator', source: 'Batch10模板脚本', required: true },
        ],
      },
      {
        id: 't_erp_owner_approval_required_evidence_matrix', name: 'erp_owner_approval_required_evidence_matrix', desc: 'ERP owner approval逐项证据需求矩阵；列出URI、acceptance criteria和禁止展示内容',
        updateFreq: '每次审批模板生成', upstream: ['erp_owner_approval_backlog', 'erp_owner_approval_intake_contract', 'tmp/exports/erp-owner-approval-record-template-batch10-20260626/erp_owner_approval_required_evidence_matrix.csv'], downstream: ['erp_owner_approval_record_input_template', 'erp_owner_approval_preflight_result', 'erp_owner_approval_validation_result'],
        fields: [
          { name: 'approval_item_id', type: 'VARCHAR(180)', desc: 'Batch8 backlog审批项ID', source: 'erp_owner_approval_backlog', required: true },
          { name: 'required_evidence', type: 'TEXT', desc: '升级证据所需材料', source: 'erp_owner_approval_backlog', required: true },
          { name: 'acceptance_criteria', type: 'TEXT', desc: '可审计、带日期、scope清晰且保留禁止展示规则', source: '证据门禁', required: true },
          { name: 'required_uri_scheme', type: 'TEXT', desc: '允许的审批记录URI scheme', source: 'Batch10模板脚本', required: true },
          { name: 'forbidden_raw_values', type: 'TEXT', desc: '禁止进入页面或CSV事实导出的原始业务值', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_approval_submission_readiness', name: 'erp_owner_approval_submission_readiness', desc: 'ERP owner approval提交readiness；按release gate列出缺失owner records数量',
        updateFreq: '每次审批模板生成/owner回填后', upstream: ['erp_owner_approval_release_gate', 'tmp/exports/erp-owner-approval-record-template-batch10-20260626/erp_owner_approval_submission_readiness.csv'], downstream: ['erp_owner_submission_release_readiness', 'erp_owner_approval_release_preflight_summary', 'erp_owner_approval_validation_result', 'erp_owner_approval_release_gate'],
        fields: [
          { name: 'release_gate_id', type: 'VARCHAR(180)', desc: 'Batch9 release gate ID', source: 'erp_owner_approval_release_gate', required: true },
          { name: 'required_owner_records', type: 'INT', desc: '该release gate所需owner records数量', source: 'Batch9 release gate', required: true },
          { name: 'template_rows_available', type: 'INT', desc: 'Batch10已准备可填写模板行数', source: 'Batch10模板脚本', required: true },
          { name: 'submitted_owner_records', type: 'INT', desc: '当前0', source: 'Batch10模板脚本', required: true },
          { name: 'missing_owner_records', type: 'INT', desc: '仍缺owner records数量', source: 'Batch10模板脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_approval_preflight_rulebook', name: 'erp_owner_approval_preflight_rulebook', desc: 'ERP owner approval提交前预检规则；Batch11定义Batch9 handoff前置条件',
        updateFreq: '每次预检规则变更', upstream: ['erp_owner_approval_record_input_template', 'tmp/exports/erp-owner-approval-preflight-batch11-20260626/erp_owner_approval_preflight_rulebook.csv'], downstream: ['erp_owner_approval_preflight_result'],
        fields: [
          { name: 'rule_id', type: 'VARCHAR(180)', desc: '预检规则ID', source: 'Batch11预检脚本', required: true },
          { name: 'rule_name', type: 'VARCHAR(160)', desc: '规则名称', source: '证据门禁', required: true },
          { name: 'required_condition', type: 'TEXT', desc: 'Batch9 handoff前必须满足的条件', source: '证据门禁', required: true },
          { name: 'failure_status', type: 'VARCHAR(120)', desc: '不满足时的阻断状态', source: 'Batch11预检脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_approval_preflight_result', name: 'erp_owner_approval_preflight_result', desc: 'ERP owner approval逐行提交前预检结果；当前Batch10空模板全部blocked',
        updateFreq: '每次owner记录回填后', upstream: ['erp_owner_approval_record_input_template', 'erp_owner_approval_preflight_rulebook', 'tmp/exports/erp-owner-approval-preflight-batch11-20260626/erp_owner_approval_preflight_result.csv'], downstream: ['erp_owner_approval_batch9_handoff_queue', 'erp_owner_approval_validation_result'],
        fields: [
          { name: 'preflight_id', type: 'VARCHAR(220)', desc: '预检结果ID', source: 'Batch11预检脚本', required: true },
          { name: 'approval_item_id', type: 'VARCHAR(180)', desc: 'Batch8 backlog审批项ID', source: 'erp_owner_approval_record_input_template', required: true },
          { name: 'preflight_status', type: 'VARCHAR(120)', desc: '当前blocked_preflight', source: 'Batch11预检脚本', required: true },
          { name: 'preflight_messages', type: 'TEXT', desc: '缺失或阻断原因', source: '证据门禁', required: true },
          { name: 'ready_for_batch9_validator', type: 'BOOLEAN', desc: '当前false', source: 'Batch11预检脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_approval_forbidden_value_scan', name: 'erp_owner_approval_forbidden_value_scan', desc: 'ERP owner approval回填记录禁用raw value扫描；不输出命中原文',
        updateFreq: '每次owner记录回填后', upstream: ['erp_owner_approval_record_input_template', 'tmp/exports/erp-owner-approval-preflight-batch11-20260626/erp_owner_approval_forbidden_value_scan.csv'], downstream: ['erp_owner_approval_preflight_result'],
        fields: [
          { name: 'scan_id', type: 'VARCHAR(220)', desc: '禁用值扫描ID', source: 'Batch11预检脚本', required: true },
          { name: 'approval_item_id', type: 'VARCHAR(180)', desc: '对应审批项ID', source: 'erp_owner_approval_record_input_template', required: true },
          { name: 'forbidden_pattern_hits', type: 'INT', desc: '禁用模式命中数量；不记录命中文本', source: 'Batch11预检脚本', required: true },
          { name: 'scan_status', type: 'VARCHAR(120)', desc: '当前passed_no_forbidden_patterns', source: 'Batch11预检脚本', required: true },
          { name: 'redaction_action', type: 'TEXT', desc: '命中时要求先移除raw values再进入Batch9', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_approval_batch9_handoff_queue', name: 'erp_owner_approval_batch9_handoff_queue', desc: 'ERP owner approval进入Batch9 validator的handoff队列；当前0行',
        updateFreq: '每次预检通过后', upstream: ['erp_owner_approval_preflight_result', 'tmp/exports/erp-owner-approval-preflight-batch11-20260626/erp_owner_approval_batch9_handoff_queue.csv'], downstream: ['erp_owner_approval_validation_result'],
        fields: [
          { name: 'handoff_id', type: 'VARCHAR(220)', desc: 'handoff队列ID；当前无候选', source: 'Batch11预检脚本', required: true },
          { name: 'approval_records_path', type: 'TEXT', desc: '将传给Batch9 validator的审批记录路径', source: 'Batch11预检脚本', required: true },
          { name: 'ready_rows', type: 'INT', desc: '可进入Batch9的行数；当前0', source: 'Batch11预检脚本', required: true },
          { name: 'batch9_validator_command', type: 'TEXT', desc: '后续Batch9校验命令', source: 'Batch11预检脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_approval_release_preflight_summary', name: 'erp_owner_approval_release_preflight_summary', desc: 'ERP release gate维度预检汇总；当前9个release gate均无可handoff记录',
        updateFreq: '每次预检后', upstream: ['erp_owner_approval_submission_readiness', 'erp_owner_approval_preflight_result', 'tmp/exports/erp-owner-approval-preflight-batch11-20260626/erp_owner_approval_release_preflight_summary.csv'], downstream: ['erp_owner_approval_release_gate', 'dashboard_kpi', 'CSV exports'],
        fields: [
          { name: 'release_gate_id', type: 'VARCHAR(180)', desc: 'Batch9 release gate ID', source: 'erp_owner_approval_release_gate', required: true },
          { name: 'required_owner_records', type: 'INT', desc: '该release gate需要的owner records', source: 'Batch10 readiness', required: true },
          { name: 'preflight_ready_rows', type: 'INT', desc: '当前预检可handoff行数', source: 'Batch11预检脚本', required: true },
          { name: 'handoff_status', type: 'VARCHAR(140)', desc: '当前blocked_no_preflight_ready_records', source: 'Batch11预检脚本', required: true },
          { name: 'can_export', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_intake_inventory', name: 'erp_owner_submission_intake_inventory', desc: 'ERP owner提交目录盘点；Batch12检测真实审批CSV是否到达',
        updateFreq: '每次owner提交目录变化后', upstream: ['tmp/inputs/erp-owner-approval-submissions-batch12', 'tmp/exports/erp-owner-submission-intake-batch12-20260626/erp_owner_submission_intake_inventory.csv'], downstream: ['erp_owner_submission_schema_audit', 'erp_owner_submission_redaction_audit'],
        fields: [
          { name: 'submission_dir', type: 'TEXT', desc: 'owner审批CSV提交目录', source: 'Batch12提交审计脚本', required: true },
          { name: 'file_path', type: 'TEXT', desc: '检测到的CSV路径；默认仅记录缺失目录', source: 'Batch12提交审计脚本', required: true },
          { name: 'row_count', type: 'INT', desc: 'CSV数据行数；当前0', source: 'Batch12提交审计脚本', required: true },
          { name: 'sha256', type: 'VARCHAR(64)', desc: '提交文件hash；当前为空', source: 'Batch12提交审计脚本', required: false },
          { name: 'inventory_status', type: 'VARCHAR(140)', desc: '当前blocked_missing_submission_directory', source: 'Batch12提交审计脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_schema_audit', name: 'erp_owner_submission_schema_audit', desc: 'ERP owner提交CSV schema审计；逐项比对Batch10模板的23条approval_item_id',
        updateFreq: '每次owner提交目录变化后', upstream: ['erp_owner_approval_record_input_template', 'erp_owner_submission_intake_inventory', 'tmp/exports/erp-owner-submission-intake-batch12-20260626/erp_owner_submission_schema_audit.csv'], downstream: ['erp_owner_submission_batch11_queue', 'erp_owner_submission_release_readiness'],
        fields: [
          { name: 'schema_audit_id', type: 'VARCHAR(220)', desc: 'schema审计ID', source: 'Batch12提交审计脚本', required: true },
          { name: 'approval_item_id', type: 'VARCHAR(180)', desc: 'Batch10模板审批项ID', source: 'erp_owner_approval_record_input_template', required: true },
          { name: 'matched_submission_rows', type: 'INT', desc: '匹配到的真实提交行数；当前0', source: 'Batch12提交审计脚本', required: true },
          { name: 'missing_required_fields', type: 'TEXT', desc: '缺失字段清单；不回显字段值', source: 'Batch12提交审计脚本', required: true },
          { name: 'schema_status', type: 'VARCHAR(140)', desc: '当前blocked_missing_submission_record', source: 'Batch12提交审计脚本', required: true },
          { name: 'ready_for_batch11_preflight', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_redaction_audit', name: 'erp_owner_submission_redaction_audit', desc: 'ERP owner提交CSV脱敏审计；只记录禁用值命中数量，不输出命中文本',
        updateFreq: '每次owner提交目录变化后', upstream: ['erp_owner_submission_intake_inventory', 'tmp/exports/erp-owner-submission-intake-batch12-20260626/erp_owner_submission_redaction_audit.csv'], downstream: ['erp_owner_submission_batch11_queue'],
        fields: [
          { name: 'redaction_audit_id', type: 'VARCHAR(220)', desc: '脱敏审计ID', source: 'Batch12提交审计脚本', required: true },
          { name: 'approval_item_id', type: 'VARCHAR(180)', desc: 'Batch10模板审批项ID', source: 'erp_owner_approval_record_input_template', required: true },
          { name: 'submitted_rows_scanned', type: 'INT', desc: '扫描提交行数；当前0', source: 'Batch12提交审计脚本', required: true },
          { name: 'forbidden_pattern_hits', type: 'INT', desc: '禁用模式命中数量；不记录命中文本', source: 'Batch12提交审计脚本', required: true },
          { name: 'redaction_status', type: 'VARCHAR(140)', desc: '当前not_scanned_no_submission', source: 'Batch12提交审计脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_batch11_queue', name: 'erp_owner_submission_batch11_queue', desc: 'ERP owner提交CSV进入Batch11 preflight的队列；当前0行',
        updateFreq: '每次owner提交目录变化后', upstream: ['erp_owner_submission_schema_audit', 'erp_owner_submission_redaction_audit', 'tmp/exports/erp-owner-submission-intake-batch12-20260626/erp_owner_submission_batch11_queue.csv'], downstream: ['erp_owner_approval_preflight_result'],
        fields: [
          { name: 'queue_id', type: 'VARCHAR(220)', desc: 'Batch11预检队列ID；当前无候选', source: 'Batch12提交审计脚本', required: true },
          { name: 'approval_records_path', type: 'TEXT', desc: '将传给Batch11 --approval-records的CSV路径', source: 'Batch12提交审计脚本', required: true },
          { name: 'schema_ready_rows', type: 'INT', desc: 'schema可进入Batch11的行数；当前0', source: 'Batch12提交审计脚本', required: true },
          { name: 'batch11_preflight_command', type: 'TEXT', desc: '后续Batch11预检命令', source: 'Batch12提交审计脚本', required: true },
          { name: 'queue_status', type: 'VARCHAR(140)', desc: '当前无队列行', source: 'Batch12提交审计脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_release_readiness', name: 'erp_owner_submission_release_readiness', desc: 'ERP release gate维度owner提交readiness；当前9个release gate均无可预检提交',
        updateFreq: '每次owner提交目录变化后', upstream: ['erp_owner_approval_submission_readiness', 'erp_owner_submission_schema_audit', 'tmp/exports/erp-owner-submission-intake-batch12-20260626/erp_owner_submission_release_readiness.csv'], downstream: ['erp_owner_approval_release_preflight_summary', 'erp_owner_approval_release_gate'],
        fields: [
          { name: 'release_gate_id', type: 'VARCHAR(180)', desc: 'Batch9 release gate ID', source: 'erp_owner_approval_submission_readiness', required: true },
          { name: 'submitted_owner_records', type: 'INT', desc: '当前提交审批记录数；当前0', source: 'Batch12提交审计脚本', required: true },
          { name: 'schema_ready_records', type: 'INT', desc: 'schema可进入Batch11的记录数；当前0', source: 'Batch12提交审计脚本', required: true },
          { name: 'batch11_queue_rows', type: 'INT', desc: 'Batch11预检队列行数；当前0', source: 'Batch12提交审计脚本', required: true },
          { name: 'readiness_status', type: 'VARCHAR(140)', desc: '当前blocked_no_batch11_ready_submission', source: 'Batch12提交审计脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_packet_index', name: 'erp_owner_submission_packet_index', desc: 'ERP Batch13 owner submission模板包索引；combined和lane模板均不进入真实提交目录',
        updateFreq: '每次owner提交包生成', upstream: ['erp_owner_approval_record_input_template', 'tmp/exports/erp-owner-submission-pack-batch13-20260626/erp_owner_submission_packet_index.csv'], downstream: ['erp_owner_submission_template_manifest', 'erp_owner_submission_field_completion_checklist'],
        fields: [
          { name: 'packet_id', type: 'VARCHAR(180)', desc: 'Batch13模板包ID', source: 'Batch13模板包脚本', required: true },
          { name: 'template_file', type: 'TEXT', desc: '导出目录下的模板文件路径', source: 'Batch13模板包脚本', required: true },
          { name: 'approval_item_count', type: 'INT', desc: '模板内approval item数量', source: 'erp_owner_approval_record_input_template', required: true },
          { name: 'target_submission_dir', type: 'TEXT', desc: '真实owner CSV后续应提交的Batch12目录', source: '证据门禁', required: true },
          { name: 'next_batch12_command', type: 'TEXT', desc: '真实提交到达后的Batch12命令', source: 'Batch13模板包脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false；模板不代表审批通过', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_template_manifest', name: 'erp_owner_submission_template_manifest', desc: 'ERP Batch13 owner submission模板manifest；记录模板hash、可编辑字段和锁定字段',
        updateFreq: '每次owner提交包生成', upstream: ['erp_owner_submission_packet_index', 'tmp/exports/erp-owner-submission-pack-batch13-20260626/owner-submission-templates'], downstream: ['erp_owner_submission_intake_inventory'],
        fields: [
          { name: 'template_id', type: 'VARCHAR(180)', desc: 'Batch13模板ID', source: 'Batch13模板包脚本', required: true },
          { name: 'template_file', type: 'TEXT', desc: '模板文件路径', source: 'Batch13模板包脚本', required: true },
          { name: 'row_count', type: 'INT', desc: '模板行数；combined为23，lane合计23', source: 'Batch13模板包脚本', required: true },
          { name: 'editable_fields', type: 'TEXT', desc: 'owner可填写字段清单', source: '证据门禁', required: true },
          { name: 'sha256', type: 'VARCHAR(64)', desc: '模板文件hash', source: 'Batch13模板包脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false；manifest不代表真实提交', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_field_completion_checklist', name: 'erp_owner_submission_field_completion_checklist', desc: 'ERP Batch13 owner字段补全checklist；逐项列出Batch12前必须补齐的字段和URI口径',
        updateFreq: '每次owner提交包生成', upstream: ['erp_owner_approval_record_input_template', 'erp_owner_approval_required_evidence_matrix', 'tmp/exports/erp-owner-submission-pack-batch13-20260626/erp_owner_submission_field_completion_checklist.csv'], downstream: ['erp_owner_submission_schema_audit'],
        fields: [
          { name: 'checklist_id', type: 'VARCHAR(220)', desc: '字段补全清单ID', source: 'Batch13模板包脚本', required: true },
          { name: 'approval_item_id', type: 'VARCHAR(180)', desc: 'Batch10模板审批项ID', source: 'erp_owner_approval_record_input_template', required: true },
          { name: 'blank_fields_to_complete', type: 'TEXT', desc: 'owner需补齐的空字段', source: '证据门禁', required: true },
          { name: 'required_uri_scheme', type: 'TEXT', desc: '允许的审批证据URI scheme', source: 'erp_owner_approval_required_evidence_matrix', required: true },
          { name: 'owner_action', type: 'TEXT', desc: 'owner填写与提交动作', source: 'Batch13模板包脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false；checklist不应用审批', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_release_packet_matrix', name: 'erp_owner_submission_release_packet_matrix', desc: 'ERP Batch13 release gate到owner提交模板的映射；当前所有gate仍保持阻断',
        updateFreq: '每次owner提交包生成', upstream: ['erp_owner_approval_submission_readiness', 'tmp/exports/erp-owner-submission-pack-batch13-20260626/erp_owner_submission_release_packet_matrix.csv'], downstream: ['erp_owner_submission_release_readiness'],
        fields: [
          { name: 'release_gate_id', type: 'VARCHAR(180)', desc: 'Batch9 release gate ID', source: 'erp_owner_approval_submission_readiness', required: true },
          { name: 'required_owner_records', type: 'INT', desc: 'release gate所需owner records数量', source: 'Batch10 readiness', required: true },
          { name: 'submission_template_file', type: 'TEXT', desc: '对应combined模板路径', source: 'Batch13模板包脚本', required: true },
          { name: 'target_submission_dir', type: 'TEXT', desc: '真实CSV后续提交目录', source: '证据门禁', required: true },
          { name: 'next_batch12_command', type: 'TEXT', desc: '真实提交到达后的Batch12命令', source: 'Batch13模板包脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_handoff_guide', name: 'erp_owner_submission_handoff_guide', desc: 'ERP Batch13 owner提交交接指南；规定分发模板、真实提交、Batch12、Batch11、Batch9顺序',
        updateFreq: '每次owner提交包生成', upstream: ['erp_owner_submission_packet_index', 'erp_owner_submission_template_manifest', 'tmp/exports/erp-owner-submission-pack-batch13-20260626/erp_owner_submission_handoff_guide.csv'], downstream: ['erp_owner_submission_intake_inventory', 'erp_owner_submission_batch11_queue'],
        fields: [
          { name: 'step_id', type: 'VARCHAR(180)', desc: '交接步骤ID', source: 'Batch13模板包脚本', required: true },
          { name: 'step_order', type: 'INT', desc: '执行顺序', source: 'Batch13模板包脚本', required: true },
          { name: 'action', type: 'TEXT', desc: 'owner或数据治理动作', source: 'Batch13模板包脚本', required: true },
          { name: 'required_evidence', type: 'TEXT', desc: '进入下一步的证据要求', source: '证据门禁', required: true },
          { name: 'next_command', type: 'TEXT', desc: '下一步命令；无命令步骤为空', source: 'Batch13模板包脚本', required: false },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false；guide不代表真实提交', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_dropbox_status', name: 'erp_owner_submission_dropbox_status', desc: 'ERP Batch14 owner提交dropbox状态；只读检查Batch12 input目录是否有真实CSV',
        updateFreq: '每次dropbox检查', upstream: ['erp_owner_submission_template_manifest', 'erp_owner_submission_intake_inventory', 'tmp/exports/erp-owner-submission-dropbox-watchlist-batch14-20260627/erp_owner_submission_dropbox_status.csv'], downstream: ['erp_owner_submission_owner_action_queue', 'erp_owner_submission_release_watchlist'],
        fields: [
          { name: 'dropbox_id', type: 'VARCHAR(180)', desc: 'Batch14 dropbox检查ID', source: 'Batch14 watchlist脚本', required: true },
          { name: 'target_submission_dir', type: 'TEXT', desc: 'Batch12真实owner CSV目标目录', source: '证据门禁', required: true },
          { name: 'directory_exists', type: 'BOOLEAN', desc: '当前false；脚本不创建目录', source: 'Batch14 watchlist脚本', required: true },
          { name: 'csv_file_count', type: 'INT', desc: '当前0；只计数CSV文件', source: 'Batch14 watchlist脚本', required: true },
          { name: 'current_status', type: 'VARCHAR(140)', desc: '当前blocked_no_owner_submission_csv', source: 'Batch14 watchlist脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_owner_action_queue', name: 'erp_owner_submission_owner_action_queue', desc: 'ERP Batch14 owner action queue；把23条approval item映射到模板、字段和Batch12命令',
        updateFreq: '每次dropbox检查', upstream: ['erp_owner_submission_field_completion_checklist', 'erp_owner_submission_dropbox_status', 'tmp/exports/erp-owner-submission-dropbox-watchlist-batch14-20260627/erp_owner_submission_owner_action_queue.csv'], downstream: ['erp_owner_submission_schema_audit'],
        fields: [
          { name: 'action_id', type: 'VARCHAR(220)', desc: 'owner action ID', source: 'Batch14 watchlist脚本', required: true },
          { name: 'approval_item_id', type: 'VARCHAR(180)', desc: 'Batch10模板审批项ID', source: 'erp_owner_submission_field_completion_checklist', required: true },
          { name: 'template_file', type: 'TEXT', desc: '应填写的Batch13模板路径', source: 'erp_owner_submission_template_manifest', required: true },
          { name: 'blank_fields_to_complete', type: 'TEXT', desc: 'owner需补齐的空字段', source: '证据门禁', required: true },
          { name: 'next_batch12_command', type: 'TEXT', desc: '真实CSV到达后的Batch12命令', source: 'Batch14 watchlist脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false；action queue不应用审批', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_template_distribution', name: 'erp_owner_submission_template_distribution', desc: 'ERP Batch14 模板分发清单；列出可分发模板、hash、owner role和提交目录',
        updateFreq: '每次dropbox检查', upstream: ['erp_owner_submission_template_manifest', 'erp_owner_submission_packet_index', 'tmp/exports/erp-owner-submission-dropbox-watchlist-batch14-20260627/erp_owner_submission_template_distribution.csv'], downstream: ['erp_owner_submission_owner_action_queue'],
        fields: [
          { name: 'distribution_id', type: 'VARCHAR(220)', desc: '模板分发ID', source: 'Batch14 watchlist脚本', required: true },
          { name: 'template_id', type: 'VARCHAR(180)', desc: 'Batch13模板ID', source: 'erp_owner_submission_template_manifest', required: true },
          { name: 'template_file', type: 'TEXT', desc: '模板文件路径', source: 'erp_owner_submission_template_manifest', required: true },
          { name: 'sha256', type: 'VARCHAR(64)', desc: '模板hash', source: 'erp_owner_submission_template_manifest', required: true },
          { name: 'distribution_status', type: 'VARCHAR(140)', desc: '当前ready_to_distribute_template_only', source: 'Batch14 watchlist脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false；模板分发不代表审批完成', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_release_watchlist', name: 'erp_owner_submission_release_watchlist', desc: 'ERP Batch14 release watchlist；按release gate跟踪owner CSV、Batch12 readiness和Batch11 queue',
        updateFreq: '每次dropbox检查', upstream: ['erp_owner_submission_release_packet_matrix', 'erp_owner_submission_dropbox_status', 'tmp/exports/erp-owner-submission-dropbox-watchlist-batch14-20260627/erp_owner_submission_release_watchlist.csv'], downstream: ['erp_owner_submission_release_readiness', 'erp_owner_approval_release_preflight_summary'],
        fields: [
          { name: 'watchlist_id', type: 'VARCHAR(220)', desc: 'release watch ID', source: 'Batch14 watchlist脚本', required: true },
          { name: 'release_gate_id', type: 'VARCHAR(180)', desc: 'Batch9 release gate ID', source: 'erp_owner_submission_release_packet_matrix', required: true },
          { name: 'submitted_owner_records', type: 'INT', desc: '当前0', source: 'Batch14 watchlist脚本', required: true },
          { name: 'ready_for_batch12_rows', type: 'INT', desc: '当前0', source: 'Batch14 watchlist脚本', required: true },
          { name: 'batch11_queue_rows', type: 'INT', desc: '当前0', source: 'Batch12 intake manifest', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_command_runbook', name: 'erp_owner_submission_command_runbook', desc: 'ERP Batch14 command runbook；定义dropbox检查、owner提交、Batch12、Batch11、Batch9命令顺序',
        updateFreq: '每次dropbox检查', upstream: ['erp_owner_submission_handoff_guide', 'tmp/exports/erp-owner-submission-dropbox-watchlist-batch14-20260627/erp_owner_submission_command_runbook.csv'], downstream: ['erp_owner_submission_intake_inventory', 'erp_owner_approval_preflight_result', 'erp_owner_approval_validation_result'],
        fields: [
          { name: 'step_id', type: 'VARCHAR(180)', desc: '命令步骤ID', source: 'Batch14 watchlist脚本', required: true },
          { name: 'step_order', type: 'INT', desc: '执行顺序', source: 'Batch14 watchlist脚本', required: true },
          { name: 'command', type: 'TEXT', desc: '下一步命令或人工动作', source: 'Batch14 watchlist脚本', required: true },
          { name: 'prerequisite', type: 'TEXT', desc: '进入命令前置条件', source: '证据门禁', required: true },
          { name: 'current_status', type: 'VARCHAR(140)', desc: '当前多为blocked_until_owner_csv_exists', source: 'Batch14 watchlist脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false；runbook不是审批记录', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_acceptance_rulebook', name: 'erp_owner_submission_acceptance_rulebook', desc: 'ERP Batch15 owner提交acceptance规则表；定义真实CSV进入Batch12前的接收条件',
        updateFreq: '每次acceptance gate检查', upstream: ['erp_owner_submission_command_runbook', 'tmp/exports/erp-owner-submission-acceptance-gate-batch15-20260627/erp_owner_submission_acceptance_rulebook.csv'], downstream: ['erp_owner_submission_acceptance_result', 'erp_owner_submission_release_acceptance_matrix'],
        fields: [
          { name: 'rule_id', type: 'VARCHAR(180)', desc: 'Batch15 acceptance规则ID', source: 'Batch15 acceptance gate脚本', required: true },
          { name: 'rule_name', type: 'VARCHAR(180)', desc: '规则名称', source: 'Batch15 acceptance gate脚本', required: true },
          { name: 'required_condition', type: 'TEXT', desc: '接收所需前置条件', source: '证据门禁', required: true },
          { name: 'acceptance_status', type: 'VARCHAR(140)', desc: '当前blocked_awaiting_real_owner_csv', source: 'Batch15 acceptance gate脚本', required: true },
          { name: 'next_check', type: 'TEXT', desc: '下一步检查点', source: 'Batch15 acceptance gate脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false；规则不代表真实审批', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_acceptance_result', name: 'erp_owner_submission_acceptance_result', desc: 'ERP Batch15 owner提交acceptance结果；逐项标记23条approval item的接收状态',
        updateFreq: '每次acceptance gate检查', upstream: ['erp_owner_submission_owner_action_queue', 'erp_owner_submission_acceptance_rulebook', 'tmp/exports/erp-owner-submission-acceptance-gate-batch15-20260627/erp_owner_submission_acceptance_result.csv'], downstream: ['erp_owner_submission_schema_audit', 'erp_owner_submission_escalation_queue'],
        fields: [
          { name: 'acceptance_id', type: 'VARCHAR(220)', desc: 'acceptance结果ID', source: 'Batch15 acceptance gate脚本', required: true },
          { name: 'approval_item_id', type: 'VARCHAR(180)', desc: 'Batch10模板审批项ID', source: 'erp_owner_submission_owner_action_queue', required: true },
          { name: 'template_file', type: 'TEXT', desc: '应提交的owner模板路径', source: 'erp_owner_submission_owner_action_queue', required: true },
          { name: 'acceptance_status', type: 'VARCHAR(140)', desc: '当前blocked_awaiting_real_owner_csv', source: 'Batch15 acceptance gate脚本', required: true },
          { name: 'missing_acceptance_inputs', type: 'TEXT', desc: '进入Batch12前仍缺的字段或证据', source: '证据门禁', required: true },
          { name: 'next_batch12_command', type: 'TEXT', desc: '真实CSV到达后的Batch12命令', source: 'Batch15 acceptance gate脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false；acceptance result不应用审批', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_evidence_uri_contract', name: 'erp_owner_submission_evidence_uri_contract', desc: 'ERP Batch15 evidence URI合同；按approval lane约束审批证据URI口径',
        updateFreq: '每次acceptance gate检查', upstream: ['erp_owner_submission_field_completion_checklist', 'tmp/exports/erp-owner-submission-acceptance-gate-batch15-20260627/erp_owner_submission_evidence_uri_contract.csv'], downstream: ['erp_owner_approval_preflight_result', 'erp_owner_submission_acceptance_result'],
        fields: [
          { name: 'contract_id', type: 'VARCHAR(220)', desc: 'URI合同ID', source: 'Batch15 acceptance gate脚本', required: true },
          { name: 'approval_lane', type: 'VARCHAR(120)', desc: '审批lane', source: 'erp_owner_submission_field_completion_checklist', required: true },
          { name: 'owner_roles', type: 'TEXT', desc: '该lane所需owner角色', source: 'erp_owner_submission_field_completion_checklist', required: true },
          { name: 'required_uri_scheme', type: 'TEXT', desc: '允许的审批证据URI scheme', source: '证据门禁', required: true },
          { name: 'required_fields', type: 'TEXT', desc: '该lane必填字段组合', source: 'erp_owner_submission_field_completion_checklist', required: true },
          { name: 'forbidden_values_policy', type: 'TEXT', desc: '禁止输出原始SKU、产品、客户、运营、仓库、凭据或审批备注正文', source: '隐私治理', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false；URI合同不代表真实审批证据已存在', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_release_acceptance_matrix', name: 'erp_owner_submission_release_acceptance_matrix', desc: 'ERP Batch15 release acceptance矩阵；按release gate汇总owner提交接收状态',
        updateFreq: '每次acceptance gate检查', upstream: ['erp_owner_submission_release_watchlist', 'erp_owner_submission_acceptance_rulebook', 'tmp/exports/erp-owner-submission-acceptance-gate-batch15-20260627/erp_owner_submission_release_acceptance_matrix.csv'], downstream: ['erp_owner_submission_release_readiness', 'erp_owner_approval_release_preflight_summary'],
        fields: [
          { name: 'release_acceptance_id', type: 'VARCHAR(220)', desc: 'release acceptance ID', source: 'Batch15 acceptance gate脚本', required: true },
          { name: 'release_gate_id', type: 'VARCHAR(180)', desc: 'Batch9 release gate ID', source: 'erp_owner_submission_release_watchlist', required: true },
          { name: 'accepted_owner_records', type: 'INT', desc: '当前0；真实owner CSV尚未接收', source: 'Batch15 acceptance gate脚本', required: true },
          { name: 'ready_for_batch12_rows', type: 'INT', desc: '当前0', source: 'Batch14 release watchlist', required: true },
          { name: 'acceptance_status', type: 'VARCHAR(140)', desc: '当前blocked_awaiting_real_owner_csv', source: 'Batch15 acceptance gate脚本', required: true },
          { name: 'can_export', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_escalation_queue', name: 'erp_owner_submission_escalation_queue', desc: 'ERP Batch15 escalation queue；把23条仍需owner输入的项转成升级队列',
        updateFreq: '每次acceptance gate检查', upstream: ['erp_owner_submission_acceptance_result', 'tmp/exports/erp-owner-submission-acceptance-gate-batch15-20260627/erp_owner_submission_escalation_queue.csv'], downstream: ['erp_owner_submission_owner_action_queue', 'erp_owner_submission_dropbox_status'],
        fields: [
          { name: 'escalation_id', type: 'VARCHAR(220)', desc: '升级队列ID', source: 'Batch15 acceptance gate脚本', required: true },
          { name: 'approval_item_id', type: 'VARCHAR(180)', desc: 'Batch10模板审批项ID', source: 'erp_owner_submission_acceptance_result', required: true },
          { name: 'owner_role', type: 'VARCHAR(160)', desc: '所需owner角色', source: 'erp_owner_submission_owner_action_queue', required: true },
          { name: 'owner_action', type: 'TEXT', desc: 'owner下一步动作', source: 'erp_owner_submission_owner_action_queue', required: true },
          { name: 'escalation_status', type: 'VARCHAR(140)', desc: '当前owner_input_required', source: 'Batch15 acceptance gate脚本', required: true },
          { name: 'next_command', type: 'TEXT', desc: '下一次dropbox检查命令', source: 'Batch15 acceptance gate脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前false；升级队列不代表审批完成', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_synthetic_record', name: 'synthetic_owner_approval_records_batch16', desc: 'ERP Batch16 synthetic owner approval records；虚拟填充23条审批记录，仅用于Batch12/11/9 dry-run',
        updateFreq: '按需生成', upstream: ['erp_owner_approval_record_input_template', 'tmp/inputs/erp-owner-approval-submissions-batch12-synthetic/synthetic_owner_approval_records_batch16.csv'], downstream: ['erp_owner_submission_synthetic_record_fill_audit', 'erp_owner_submission_synthetic_gate_plan'],
        fields: [
          { name: 'approval_item_id', type: 'VARCHAR(180)', desc: 'Batch10模板审批项ID', source: 'Batch10 owner record模板', required: true },
          { name: 'approval_lane', type: 'VARCHAR(120)', desc: '审批lane', source: 'Batch10 owner record模板', required: true },
          { name: 'approval_decision', type: 'VARCHAR(80)', desc: '虚拟填充值approved；仅作流程演练', source: 'Batch16 synthetic fixture脚本', required: true },
          { name: 'approver_name_hash', type: 'VARCHAR(64)', desc: 'synthetic hash；不代表真实审批人', source: 'Batch16 synthetic fixture脚本', required: true },
          { name: 'approval_record_uri', type: 'TEXT', desc: 'file-hash:// synthetic URI；不代表真实审批凭证', source: 'Batch16 synthetic fixture脚本', required: true },
          { name: 'evidence_grade', type: 'VARCHAR(40)', desc: '固定L2-fixture-or-dry-run', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '固定false；虚拟数据不可展示或导出', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_synthetic_fixture_index', name: 'erp_owner_submission_synthetic_fixture_index', desc: 'ERP Batch16 synthetic fixture索引；记录虚拟CSV路径、hash和用途边界',
        updateFreq: '按需生成', upstream: ['synthetic_owner_approval_records_batch16', 'tmp/exports/erp-owner-submission-synthetic-fixture-batch16-20260627/erp_owner_submission_synthetic_fixture_index.csv'], downstream: ['erp_owner_submission_synthetic_gate_plan'],
        fields: [
          { name: 'fixture_id', type: 'VARCHAR(220)', desc: 'synthetic fixture ID', source: 'Batch16 synthetic fixture脚本', required: true },
          { name: 'synthetic_input_dir', type: 'TEXT', desc: 'synthetic专用输入目录', source: 'Batch16 synthetic fixture脚本', required: true },
          { name: 'record_file_path', type: 'TEXT', desc: '虚拟审批CSV路径', source: 'Batch16 synthetic fixture脚本', required: true },
          { name: 'row_count', type: 'INT', desc: '当前23行', source: 'Batch16 synthetic fixture脚本', required: true },
          { name: 'fixture_scope', type: 'TEXT', desc: '仅用于Batch12/11/9 dry-run', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '固定false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_synthetic_record_fill_audit', name: 'erp_owner_submission_synthetic_record_fill_audit', desc: 'ERP Batch16 synthetic记录填充审计；确认虚拟hash、URI和展示/导出false',
        updateFreq: '按需生成', upstream: ['synthetic_owner_approval_records_batch16', 'tmp/exports/erp-owner-submission-synthetic-fixture-batch16-20260627/erp_owner_submission_synthetic_record_fill_audit.csv'], downstream: ['erp_owner_submission_synthetic_gate_plan'],
        fields: [
          { name: 'approval_item_id', type: 'VARCHAR(180)', desc: 'Batch10模板审批项ID', source: 'synthetic owner records', required: true },
          { name: 'approval_decision', type: 'VARCHAR(80)', desc: '虚拟填充值approved', source: 'Batch16 synthetic fixture脚本', required: true },
          { name: 'approver_hash_present', type: 'BOOLEAN', desc: '是否生成64位synthetic hash', source: 'Batch16 synthetic fixture脚本', required: true },
          { name: 'approval_record_uri_scheme', type: 'VARCHAR(80)', desc: '固定file-hash://', source: 'Batch16 synthetic fixture脚本', required: true },
          { name: 'synthetic_marker', type: 'VARCHAR(120)', desc: 'SYNTHETIC_FIXTURE_DO_NOT_USE_AS_FACT', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '固定false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_synthetic_gate_plan', name: 'erp_owner_submission_synthetic_gate_plan', desc: 'ERP Batch16 synthetic gate plan；定义Batch12、Batch11、Batch9 dry-run顺序和manual review边界',
        updateFreq: '按需生成', upstream: ['erp_owner_submission_synthetic_fixture_index', 'erp_owner_submission_synthetic_record_fill_audit', 'tmp/exports/erp-owner-submission-synthetic-fixture-batch16-20260627/erp_owner_submission_synthetic_gate_plan.csv'], downstream: ['erp_owner_submission_intake_inventory', 'erp_owner_approval_preflight_result', 'erp_owner_approval_validation_result'],
        fields: [
          { name: 'step_id', type: 'VARCHAR(220)', desc: 'dry-run步骤ID', source: 'Batch16 synthetic fixture脚本', required: true },
          { name: 'step_order', type: 'INT', desc: '执行顺序', source: 'Batch16 synthetic fixture脚本', required: true },
          { name: 'gate', type: 'VARCHAR(180)', desc: 'Batch12/Batch11/Batch9/manual review gate', source: 'Batch16 synthetic fixture脚本', required: true },
          { name: 'command', type: 'TEXT', desc: 'dry-run命令；不得作为真实审批命令', source: 'Batch16 synthetic fixture脚本', required: true },
          { name: 'can_write_real_gate', type: 'BOOLEAN', desc: '固定false', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '固定false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_synthetic_pipeline_run_matrix', name: 'erp_owner_submission_synthetic_pipeline_run_matrix', desc: 'ERP Batch17 synthetic pipeline run matrix；串联Batch12/11/9 fixture dry-run并记录证据等级',
        updateFreq: '按需生成', upstream: ['erp_owner_submission_synthetic_gate_plan', 'synthetic_owner_approval_records_batch16', 'tmp/exports/erp-owner-submission-synthetic-pipeline-batch17-20260627/erp_owner_submission_synthetic_pipeline_run_matrix.csv'], downstream: ['erp_owner_submission_synthetic_boundary_audit', 'erp_owner_submission_synthetic_release_gate_matrix'],
        fields: [
          { name: 'stage_id', type: 'VARCHAR(220)', desc: 'synthetic pipeline阶段ID', source: 'Batch17 synthetic pipeline脚本', required: true },
          { name: 'stage_order', type: 'INT', desc: '执行顺序', source: 'Batch17 synthetic pipeline脚本', required: true },
          { name: 'stage_name', type: 'VARCHAR(220)', desc: 'Batch12/Batch11/Batch9/manual review阶段', source: 'Batch17 synthetic pipeline脚本', required: true },
          { name: 'observed_evidence_grade', type: 'VARCHAR(40)', desc: '子批次必须保持L2-fixture-or-dry-run', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '固定false', source: '证据门禁', required: true },
          { name: 'can_export', type: 'BOOLEAN', desc: '固定false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_synthetic_release_gate_matrix', name: 'erp_owner_submission_synthetic_release_gate_matrix', desc: 'ERP Batch17 synthetic release gate matrix；9个release gate仅为人工复核演练',
        updateFreq: '按需生成', upstream: ['erp_owner_submission_synthetic_pipeline_run_matrix', 'erp_owner_approval_release_gate', 'tmp/exports/erp-owner-submission-synthetic-pipeline-batch17-20260627/erp_owner_submission_synthetic_release_gate_matrix.csv'], downstream: ['erp_owner_submission_synthetic_boundary_audit'],
        fields: [
          { name: 'release_gate_id', type: 'VARCHAR(220)', desc: 'release gate ID', source: 'Batch8 display approval模板', required: true },
          { name: 'table_name', type: 'VARCHAR(160)', desc: '目标治理表', source: 'Batch8 display approval模板', required: true },
          { name: 'synthetic_validation_status', type: 'VARCHAR(180)', desc: '固定dry-run only状态', source: 'Batch17 synthetic pipeline脚本', required: true },
          { name: 'ready_for_manual_review', type: 'BOOLEAN', desc: '固定false；synthetic不可进入真实人工复核', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '固定false', source: '证据门禁', required: true },
          { name: 'can_export', type: 'BOOLEAN', desc: '固定false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_submission_synthetic_boundary_audit', name: 'erp_owner_submission_synthetic_boundary_audit', desc: 'ERP Batch17 synthetic boundary audit；检查fixtureMode、L2降级、display/export/promotion为0',
        updateFreq: '按需生成', upstream: ['erp_owner_submission_synthetic_pipeline_run_matrix', 'erp_owner_submission_synthetic_release_gate_matrix', 'tmp/exports/erp-owner-submission-synthetic-pipeline-batch17-20260627/erp_owner_submission_synthetic_boundary_audit.csv'], downstream: ['erp_owner_submission_acceptance_result', 'erp_owner_approval_release_gate'],
        fields: [
          { name: 'boundary_id', type: 'VARCHAR(220)', desc: '证据边界检查ID', source: 'Batch17 synthetic pipeline脚本', required: true },
          { name: 'checked_item', type: 'TEXT', desc: '检查项', source: 'Batch17 synthetic pipeline脚本', required: true },
          { name: 'expected_value', type: 'TEXT', desc: '期望边界值', source: '证据门禁', required: true },
          { name: 'observed_value', type: 'TEXT', desc: '实际dry-run观测值', source: 'Batch17 synthetic pipeline脚本', required: true },
          { name: 'boundary_status', type: 'VARCHAR(80)', desc: 'passed或blocked', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '固定false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_real_submission_field_checklist', name: 'erp_owner_real_submission_field_checklist', desc: 'ERP Batch18 real owner submission field checklist；真实owner CSV到达前的23条回填核验清单',
        updateFreq: '真实owner提交前/模板变化时', upstream: ['erp_owner_approval_record_input_template', 'erp_owner_approval_required_evidence_matrix', 'erp_owner_submission_acceptance_result', 'tmp/exports/erp-owner-submission-real-owner-checklist-batch18-20260627/erp_owner_real_submission_field_checklist.csv'], downstream: ['erp_owner_submission_intake_inventory', 'erp_owner_approval_preflight_result'],
        fields: [
          { name: 'approval_item_id', type: 'VARCHAR(180)', desc: 'Batch10审批项ID', source: 'Batch10 owner record模板', required: true },
          { name: 'approval_lane', type: 'VARCHAR(120)', desc: '审批lane', source: 'Batch10 owner record模板', required: true },
          { name: 'required_fields', type: 'TEXT', desc: '真实owner CSV必填字段', source: 'Batch10 required evidence matrix', required: true },
          { name: 'required_uri_scheme', type: 'TEXT', desc: '允许的审批凭证URI scheme', source: 'Batch15 URI contract', required: true },
          { name: 'real_owner_record_status', type: 'VARCHAR(120)', desc: '当前awaiting_real_owner_record', source: 'Batch18 checklist脚本', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '固定false；清单不是事实数据', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_real_submission_release_gate_checklist', name: 'erp_owner_real_submission_release_gate_checklist', desc: 'ERP Batch18 real owner release gate checklist；9个release gate的真实CSV接收前核验表',
        updateFreq: '真实owner提交前/发布前', upstream: ['erp_owner_submission_release_acceptance_matrix', 'erp_owner_submission_synthetic_release_gate_matrix', 'tmp/exports/erp-owner-submission-real-owner-checklist-batch18-20260627/erp_owner_real_submission_release_gate_checklist.csv'], downstream: ['erp_owner_approval_release_gate', 'erp_owner_real_submission_swap_runbook'],
        fields: [
          { name: 'release_gate_id', type: 'VARCHAR(220)', desc: 'release gate ID', source: 'Batch15 release acceptance matrix', required: true },
          { name: 'table_name', type: 'VARCHAR(160)', desc: '目标治理表', source: 'Batch15 release acceptance matrix', required: true },
          { name: 'required_owner_records', type: 'INT', desc: '该release gate所需真实owner记录数', source: 'Batch15 release acceptance matrix', required: true },
          { name: 'synthetic_release_status', type: 'VARCHAR(180)', desc: 'Batch17演练状态，仅作流程参考', source: 'Batch17 synthetic release gate matrix', required: true },
          { name: 'can_export', type: 'BOOLEAN', desc: '固定false', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '固定false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_real_submission_swap_runbook', name: 'erp_owner_real_submission_swap_runbook', desc: 'ERP Batch18 real owner swap runbook；真实owner CSV替换synthetic演练后的七步执行手册',
        updateFreq: '真实owner提交前/运行手册变化时', upstream: ['erp_owner_real_submission_field_checklist', 'erp_owner_real_submission_release_gate_checklist', 'tmp/exports/erp-owner-submission-real-owner-checklist-batch18-20260627/erp_owner_real_submission_swap_runbook.csv'], downstream: ['erp_owner_submission_dropbox_status', 'erp_owner_submission_intake_inventory', 'erp_owner_approval_preflight_result', 'erp_owner_approval_validation_result'],
        fields: [
          { name: 'step_id', type: 'VARCHAR(220)', desc: 'runbook步骤ID', source: 'Batch18 checklist脚本', required: true },
          { name: 'step_order', type: 'INT', desc: '执行顺序', source: 'Batch18 checklist脚本', required: true },
          { name: 'runbook_step', type: 'TEXT', desc: '真实CSV接收、Batch14/12/11/9和manual release review步骤', source: 'Batch18 checklist脚本', required: true },
          { name: 'command_or_action', type: 'TEXT', desc: '命令或人工动作', source: 'Batch18 checklist脚本', required: true },
          { name: 'can_write_real_gate', type: 'BOOLEAN', desc: '固定false；本runbook不自动执行真实写入', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '固定false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_owner_real_submission_boundary_audit', name: 'erp_owner_real_submission_boundary_audit', desc: 'ERP Batch18 real owner boundary audit；确认未生成真实审批、未写真实input、未开放展示导出',
        updateFreq: '每次Batch18生成', upstream: ['erp_owner_real_submission_field_checklist', 'erp_owner_real_submission_release_gate_checklist', 'erp_owner_submission_synthetic_boundary_audit', 'tmp/exports/erp-owner-submission-real-owner-checklist-batch18-20260627/erp_owner_real_submission_boundary_audit.csv'], downstream: ['erp_owner_submission_acceptance_result', 'erp_owner_approval_release_gate'],
        fields: [
          { name: 'boundary_id', type: 'VARCHAR(220)', desc: '证据边界检查ID', source: 'Batch18 checklist脚本', required: true },
          { name: 'checked_item', type: 'TEXT', desc: '检查项', source: 'Batch18 checklist脚本', required: true },
          { name: 'expected_value', type: 'TEXT', desc: '期望边界值', source: '证据门禁', required: true },
          { name: 'observed_value', type: 'TEXT', desc: '实际观测值', source: 'Batch18 checklist脚本', required: true },
          { name: 'boundary_status', type: 'VARCHAR(80)', desc: 'passed或blocked', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '固定false', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_manual_release_review_record', name: 'erp_manual_release_review_record', desc: 'ERP Batch19 manual release review记录；放行9张内部代理表的页面展示和CSV导出',
        updateFreq: '发布/导出前', upstream: ['erp_owner_approval_promotion_manifest', 'tmp/inputs/erp-manual-release-review-submissions-batch19/manual_release_review_chat_approval_20260627.json'], downstream: ['erp_manual_release_review_decision_matrix', 'erp_manual_release_review_swap_queue', 'market_trend_monthly', 'CSV exports'],
        fields: [
          { name: 'release_review_record_id', type: 'VARCHAR(220)', desc: 'manual release review记录ID', source: 'Batch19脚本', required: true },
          { name: 'approval_record_uri', type: 'TEXT', desc: '审批记录URI，不回显敏感审批正文', source: 'Batch19脚本', required: true },
          { name: 'reviewer_hash', type: 'VARCHAR(64)', desc: 'reviewer hash或alias映射', source: 'Batch19脚本', required: true },
          { name: 'review_date', type: 'DATE', desc: 'review日期', source: 'Batch19脚本', required: true },
          { name: 'decision_scope', type: 'TEXT', desc: '覆盖Batch9 promotion candidates', source: 'Batch19脚本', required: true },
          { name: 'can_export_decision', type: 'BOOLEAN', desc: '当前true，仅限private/internal proxy', source: 'manual release review', required: true },
          { name: 'can_display_as_fact_decision', type: 'BOOLEAN', desc: '当前true，仅限private/internal proxy', source: 'manual release review', required: true },
          { name: 'deployment_authorized', type: 'BOOLEAN', desc: '当前false，生产部署需另行授权', source: '证据门禁', required: true },
          { name: 'production_write_authorized', type: 'BOOLEAN', desc: '当前false，不做生产写入', source: '证据门禁', required: true },
          { name: 'provider_calls_authorized', type: 'BOOLEAN', desc: '当前false，不调用外部provider', source: '证据门禁', required: true },
        ],
      },
      {
        id: 't_erp_manual_release_review_decision_matrix', name: 'erp_manual_release_review_decision_matrix', desc: 'ERP Batch19逐表release decision矩阵；9张表均approved_ready_for_site_data_swap',
        updateFreq: '发布/导出前', upstream: ['erp_manual_release_review_record', 'erp_owner_approval_release_gate', 'tmp/exports/erp-manual-release-review-batch19-20260627/erp_manual_release_review_decision_matrix.csv'], downstream: ['erp_manual_release_review_swap_queue', 'source_registry', 'MarketPage', 'SelfInsight', 'ChannelInterviews', 'StoreInterviews', 'RegionCompetition'],
        fields: [
          { name: 'release_review_decision_id', type: 'VARCHAR(240)', desc: '逐表release review决策ID', source: 'Batch19脚本', required: true },
          { name: 'table_name', type: 'VARCHAR(160)', desc: '被放行的治理表，如market_trend_monthly或erp_channel_growth_snapshot', source: 'Batch9 promotion manifest', required: true },
          { name: 'surface', type: 'TEXT', desc: '页面或导出使用面', source: 'Batch19脚本', required: true },
          { name: 'source_ids', type: 'TEXT', desc: 'ds-047/ds-048/ds-049/ds-050/ds-051映射', source: 'source-registry', required: true },
          { name: 'owner_records_passed', type: 'INT', desc: '通过owner validation的记录数', source: 'Batch9 validator', required: true },
          { name: 'manual_can_export_decision', type: 'BOOLEAN', desc: 'manual review导出决定', source: 'manual release review', required: true },
          { name: 'manual_can_display_as_fact_decision', type: 'BOOLEAN', desc: 'manual review展示决定', source: 'manual release review', required: true },
          { name: 'can_export', type: 'BOOLEAN', desc: '当前true，仅限internal proxy CSV', source: '证据门禁', required: true },
          { name: 'can_display_as_fact', type: 'BOOLEAN', desc: '当前true，仅限internal proxy', source: '证据门禁', required: true },
          { name: 'implementation_status', type: 'VARCHAR(120)', desc: 'pending_site_data_swap_and_verification或后续已应用状态', source: 'Batch19脚本', required: true },
        ],
      },
      {
        id: 't_erp_manual_release_review_swap_queue', name: 'erp_manual_release_review_swap_queue', desc: 'ERP Batch19 site data swap queue；把已放行表映射到页面和CSV导出',
        updateFreq: '本地site data swap时', upstream: ['erp_manual_release_review_decision_matrix', 'tmp/exports/erp-manual-release-review-batch19-20260627/erp_manual_release_review_swap_queue.csv'], downstream: ['market_trend_monthly', 'erp_sales_monthly_fact', 'erp_category_mapping', 'erp_channel_growth_snapshot', 'CSV exports'],
        fields: [
          { name: 'swap_queue_id', type: 'VARCHAR(220)', desc: 'site data swap队列ID', source: 'Batch19脚本', required: true },
          { name: 'table_name', type: 'VARCHAR(160)', desc: '目标表名', source: 'Batch19脚本', required: true },
          { name: 'surface', type: 'TEXT', desc: '页面或能力面', source: 'Batch19脚本', required: true },
          { name: 'evidence_artifact_path', type: 'TEXT', desc: '对应CSV或证据路径', source: 'Batch19脚本', required: true },
          { name: 'approved_for_display', type: 'BOOLEAN', desc: '当前true，仅限internal proxy', source: 'manual release review', required: true },
          { name: 'approved_for_export', type: 'BOOLEAN', desc: '当前true，仅限internal proxy CSV', source: 'manual release review', required: true },
          { name: 'target_status', type: 'VARCHAR(120)', desc: 'approved_internal_fact_source', source: 'Batch19脚本', required: true },
          { name: 'implementation_status', type: 'VARCHAR(120)', desc: '本地数据替换和验证状态', source: 'Batch19脚本', required: true },
          { name: 'blocking_reason', type: 'TEXT', desc: '生产部署或连接器刷新仍需单独授权时填写', source: '证据门禁', required: false },
        ],
      },
      {
        id: 't_erp_manual_release_review_boundary_audit', name: 'erp_manual_release_review_boundary_audit', desc: 'ERP Batch19证据边界审计；确认无provider call、生产写入、部署或禁用值命中',
        updateFreq: '每次manual release review', upstream: ['erp_manual_release_review_record', 'tmp/exports/erp-manual-release-review-batch19-20260627/erp_manual_release_review_boundary_audit.csv'], downstream: ['data_governance', 'release_gate', 'source_registry'],
        fields: [
          { name: 'boundary_id', type: 'VARCHAR(220)', desc: '边界审计ID', source: 'Batch19脚本', required: true },
          { name: 'checked_item', type: 'TEXT', desc: '检查项，如productionWrites/providerCalls/deployment', source: 'Batch19脚本', required: true },
          { name: 'expected_value', type: 'TEXT', desc: '期望边界值', source: '证据门禁', required: true },
          { name: 'observed_value', type: 'TEXT', desc: '实际观测值', source: 'Batch19脚本', required: true },
          { name: 'boundary_status', type: 'VARCHAR(80)', desc: 'passed或blocked', source: 'Batch19脚本', required: true },
          { name: 'evidence_grade', type: 'VARCHAR(40)', desc: 'L3-production-read-only', source: '证据门禁', required: true },
          { name: 'privacy_level', type: 'VARCHAR(40)', desc: 'private/internal', source: '证据门禁', required: true },
        ],
      },
    ],
  }
];
