import type { DataGovernance } from './model';

const dataCatalogSourceIds = ['ds-027'];
const erpGovernanceSourceIds = ['ds-027', 'ds-047', 'ds-048', 'ds-049', 'ds-050', 'ds-051'];

export const tableGovernance: Record<string, DataGovernance> = {
  t_mkt_size:     { layer: 'app', scope: 'external', sensitivity: 'L2-内部', status: 'governed', owner: '市场分析组', steward: '张分析师', qualityScore: 88, freshness: '半月manifest复核', retention: '5年', pii: false },
  t_mkt_trend:    { layer: 'app', scope: 'external', sensitivity: 'L2-内部', status: 'governed', owner: '市场分析组', steward: '张分析师', qualityScore: 85, freshness: '半月manifest复核', retention: '3年', pii: false },
  t_pest:         { layer: 'app', scope: 'external', sensitivity: 'L2-内部', status: 'pending', owner: '战略部', steward: '李研究员', qualityScore: 72, freshness: '公开来源复核中', retention: '3年', pii: false },
  t_porter:       { layer: 'app', scope: 'hybrid', sensitivity: 'L2-内部', status: 'pending', owner: '战略部', steward: '李研究员', qualityScore: 78, freshness: '人工评估待复核', retention: '3年', pii: false },
  t_customs:      { layer: 'source', scope: 'external', sensitivity: 'L2-内部', status: 'governed', owner: '供应链组', steward: '王运营', qualityScore: 92, freshness: '海关凭证待接入', retention: '7年', pii: false },
  t_category:     { layer: 'app', scope: 'external', sensitivity: 'L2-内部', status: 'governed', owner: '品类管理组', steward: '赵运营', qualityScore: 90, freshness: '连接器待接入', retention: '2年', pii: false },
  t_comp_product: { layer: 'source', scope: 'external', sensitivity: 'L2-内部', status: 'governed', owner: '竞品情报组', steward: '刘分析师', qualityScore: 94, freshness: '连接器待接入', retention: '2年', pii: false },
  t_new_product:  { layer: 'app', scope: 'hybrid', sensitivity: 'L2-内部', status: 'governed', owner: '竞品情报组', steward: '刘分析师', qualityScore: 82, freshness: '连接器待接入', retention: '2年', pii: false },
  t_region_comp:  { layer: 'app', scope: 'hybrid', sensitivity: 'L2-内部', status: 'governed', owner: '竞品情报组', steward: '刘分析师', qualityScore: 78, freshness: '连接器待接入', retention: '2年', pii: false },
  t_price:        { layer: 'source', scope: 'external', sensitivity: 'L2-内部', status: 'governed', owner: '定价组', steward: '陈分析师', qualityScore: 93, freshness: '连接器待接入', retention: '1年', pii: false },
  t_persona:      { layer: 'app', scope: 'hybrid', sensitivity: 'L2-内部', status: 'governed', owner: '用户研究组', steward: '孙研究员', qualityScore: 92, freshness: '人工凭证待接入', retention: '3年', pii: true },
  t_social:       { layer: 'source', scope: 'external', sensitivity: 'L2-内部', status: 'governed', owner: '社媒组', steward: '周运营', qualityScore: 88, freshness: '连接器待接入', retention: '1年', pii: false },
  t_comment:      { layer: 'source', scope: 'external', sensitivity: 'L3-机密', status: 'governed', owner: '用户研究组', steward: '孙研究员', qualityScore: 91, freshness: 'VOC凭证待接入', retention: '2年', pii: true },
  t_consumer_iv:  { layer: 'source', scope: 'internal', sensitivity: 'L3-机密', status: 'governed', owner: '用户研究组', steward: '孙研究员', qualityScore: 88, freshness: '访谈凭证待接入', retention: '5年', pii: true },
  t_rfm:          { layer: 'app', scope: 'internal', sensitivity: 'L3-机密', status: 'governed', owner: 'CRM组', steward: '吴数据', qualityScore: 86, freshness: 'CRM待接入', retention: '3年', pii: true },
  t_policy:       { layer: 'source', scope: 'external', sensitivity: 'L1-公开', status: 'governed', owner: '合规组', steward: '郑法务', qualityScore: 90, freshness: '公开来源复核中', retention: '永久', pii: false },
  t_supply:       { layer: 'source', scope: 'internal', sensitivity: 'L2-内部', status: 'governed', owner: '供应链组', steward: '王运营', qualityScore: 84, freshness: 'ERP待接入', retention: '5年', pii: false },
  t_ip:           { layer: 'source', scope: 'external', sensitivity: 'L1-公开', status: 'governed', owner: 'IP组', steward: '马法务', qualityScore: 95, freshness: '公开来源复核中', retention: '永久', pii: false },
  t_exhibition:   { layer: 'source', scope: 'external', sensitivity: 'L1-公开', status: 'pending', owner: '市场组', steward: '何运营', qualityScore: 85, freshness: '公开来源复核中', retention: '3年', pii: false },
  t_own_product:  { layer: 'store', scope: 'internal', sensitivity: 'L2-内部', status: 'governed', owner: '产品组', steward: '林产品', qualityScore: 96, freshness: 'ERP待接入', retention: '永久', pii: false },
  t_price_strategy:{ layer: 'app', scope: 'internal', sensitivity: 'L2-内部', status: 'governed', owner: '定价组', steward: '陈分析师', qualityScore: 92, freshness: '人工策略待复核', retention: '2年', pii: false },
  t_channel:      { layer: 'app', scope: 'internal', sensitivity: 'L2-内部', status: 'governed', owner: '渠道组', steward: '王运营', qualityScore: 89, freshness: '人工凭证待接入', retention: '3年', pii: false },
  t_promo:        { layer: 'app', scope: 'internal', sensitivity: 'L2-内部', status: 'governed', owner: '市场组', steward: '何运营', qualityScore: 87, freshness: '人工策略待复核', retention: '3年', pii: false },
  t_ai_dataset_manifest: { layer: 'clean', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: 'AI组', steward: '数据治理组', qualityScore: 72, freshness: 'Batch4 readiness已生成', retention: '3年', pii: false },
  t_ai_model_run_manifest: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: 'AI组', steward: '黄算法', qualityScore: 68, freshness: '模型运行审计待接入', retention: '2年', pii: false },
  t_ai_human_review_gate: { layer: 'app', scope: 'internal', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务复核人', qualityScore: 70, freshness: '人工复核门禁待审批', retention: '5年', pii: false },
  t_report_generation_queue: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '报告组', steward: '数据治理组', qualityScore: 70, freshness: 'Batch4队列已生成', retention: '5年', pii: false },
  t_ai_erp_context_bridge: { layer: 'clean', scope: 'internal', sensitivity: 'L3-机密', status: 'pending', owner: 'AI组', steward: 'ERP数据管理员', qualityScore: 69, freshness: 'ERP上下文桥接待审批', retention: '3年', pii: false },
  t_ai_review_sample_manifest: { layer: 'clean', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '用户研究组', steward: '数据治理组', qualityScore: 71, freshness: 'Batch5样本gate已生成', retention: '3年', pii: true },
  t_ai_review_eval_queue: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: 'AI组', steward: '黄算法', qualityScore: 68, freshness: 'Batch5 eval队列已生成', retention: '2年', pii: false },
  t_ai_review_human_queue: { layer: 'app', scope: 'internal', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务复核人', qualityScore: 70, freshness: 'Batch5人工复核队列已生成', retention: '5年', pii: false },
  t_ai_review_publish_gate: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务复核人', qualityScore: 72, freshness: 'Batch5发布门禁已生成', retention: '5年', pii: false },
  t_ai_design_run_manifest: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: 'AI组', steward: '黄算法', qualityScore: 68, freshness: 'Batch6生成run gate已生成', retention: '2年', pii: false },
  t_ai_design_asset_hash_manifest: { layer: 'clean', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '创意组', steward: '数据治理组', qualityScore: 70, freshness: 'Batch6资产hash gate已生成', retention: '3年', pii: false },
  t_ai_design_cost_queue: { layer: 'app', scope: 'internal', sensitivity: 'L3-机密', status: 'pending', owner: 'AI组', steward: '财务/数据治理组', qualityScore: 66, freshness: 'Batch6成本队列已生成', retention: '5年', pii: false, sourceIds: dataCatalogSourceIds },
  t_ai_design_commercial_review_gate: { layer: 'app', scope: 'internal', sensitivity: 'L3-机密', status: 'pending', owner: '品牌组', steward: '法务/创意负责人', qualityScore: 69, freshness: 'Batch6商用审核门禁已生成', retention: '5年', pii: false },
  t_comment_ai:   { layer: 'app', scope: 'hybrid', sensitivity: 'L2-内部', status: 'governed', owner: 'AI组', steward: '黄算法', qualityScore: 83, freshness: 'VOC凭证待接入', retention: '1年', pii: false },
  t_design_ai:    { layer: 'app', scope: 'internal', sensitivity: 'L2-内部', status: 'untracked', owner: 'AI组', steward: '黄算法', qualityScore: 60, freshness: '生成日志待接入', retention: '1年', pii: false },
  t_kb:           { layer: 'store', scope: 'internal', sensitivity: 'L2-内部', status: 'governed', owner: '知识组', steward: '冯运营', qualityScore: 88, freshness: '半月manifest复核', retention: '永久', pii: false },
  t_web_review:   { layer: 'source', scope: 'external', sensitivity: 'L3-机密', status: 'pending', owner: '爬虫组', steward: '程开发', qualityScore: 68, freshness: '网页评论凭证待接入', retention: '1年', pii: true },
  t_erp_artifact: { layer: 'source', scope: 'internal', sensitivity: 'L3-机密', status: 'governed', owner: '数据治理组', steward: 'ERP数据管理员', qualityScore: 86, freshness: 'ERP快照已取证', retention: '5年', pii: false },
  t_erp_sku:      { layer: 'store', scope: 'internal', sensitivity: 'L2-内部', status: 'governed', owner: '产品组', steward: 'ERP数据管理员', qualityScore: 82, freshness: 'Batch19内部proxy已放行', retention: '永久', pii: false },
  t_erp_sales_monthly: { layer: 'store', scope: 'internal', sensitivity: 'L3-机密', status: 'governed', owner: '销售运营组', steward: 'ERP数据管理员', qualityScore: 86, freshness: 'Batch19内部proxy已放行', retention: '5年', pii: false },
  t_erp_after_sales_monthly: { layer: 'store', scope: 'internal', sensitivity: 'L3-机密', status: 'governed', owner: '售后运营组', steward: 'ERP数据管理员', qualityScore: 84, freshness: 'Batch19内部proxy已放行', retention: '5年', pii: false },
  t_erp_retail_channel_monthly: { layer: 'store', scope: 'internal', sensitivity: 'L3-机密', status: 'governed', owner: '渠道运营组', steward: 'ERP数据管理员', qualityScore: 82, freshness: 'Batch19内部proxy已放行', retention: '5年', pii: false },
  t_erp_channel_growth: { layer: 'store', scope: 'internal', sensitivity: 'L3-机密', status: 'governed', owner: '销售运营组', steward: 'ERP数据管理员', qualityScore: 82, freshness: 'Batch19内部proxy已放行', retention: '5年', pii: false },
  t_erp_channel_target: { layer: 'store', scope: 'internal', sensitivity: 'L3-机密', status: 'governed', owner: '销售运营组', steward: 'ERP数据管理员', qualityScore: 82, freshness: 'Batch19内部proxy已放行', retention: '5年', pii: false },
  t_erp_channel_customer_dim: { layer: 'clean', scope: 'internal', sensitivity: 'L3-机密', status: 'governed', owner: '渠道运营组', steward: 'ERP数据管理员', qualityScore: 80, freshness: 'Batch19内部proxy已放行', retention: '5年', pii: false },
  t_erp_inventory_snapshot: { layer: 'source', scope: 'internal', sensitivity: 'L3-机密', status: 'pending', owner: '供应链组', steward: 'ERP数据管理员', qualityScore: 62, freshness: '库存快照待接入', retention: '5年', pii: false },
  t_erp_field_dictionary: { layer: 'clean', scope: 'internal', sensitivity: 'L2-内部', status: 'pending', owner: '数据治理组', steward: 'ERP数据管理员', qualityScore: 68, freshness: 'Batch7字段字典readiness已生成', retention: '永久', pii: false },
  t_erp_category_mapping: { layer: 'clean', scope: 'hybrid', sensitivity: 'L2-内部', status: 'governed', owner: '品类管理组', steward: 'ERP数据管理员', qualityScore: 82, freshness: 'Batch19内部proxy已放行', retention: '永久', pii: false },
  t_erp_category_review_queue: { layer: 'app', scope: 'hybrid', sensitivity: 'L2-内部', status: 'pending', owner: '品类管理组', steward: 'ERP数据管理员', qualityScore: 70, freshness: 'Batch7品类复核队列已生成', retention: '3年', pii: false },
  t_erp_subtotal_reconciliation_queue: { layer: 'app', scope: 'internal', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: 'ERP数据管理员', qualityScore: 68, freshness: 'Batch7小计复核队列已生成', retention: '5年', pii: false },
  t_erp_display_approval_gate: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 70, freshness: 'Batch7展示审批门禁已生成', retention: '5年', pii: false },
  t_erp_field_owner_approval_packet: { layer: 'app', scope: 'internal', sensitivity: 'L3-机密', status: 'pending', owner: '销售运营/售后运营组', steward: 'ERP数据管理员', qualityScore: 70, freshness: 'Batch8字段owner审批包已生成', retention: '5年', pii: false },
  t_erp_category_owner_approval_packet: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '品类管理组', steward: 'ERP数据管理员', qualityScore: 70, freshness: 'Batch8品类owner审批包已生成', retention: '5年', pii: false },
  t_erp_subtotal_owner_explanation_packet: { layer: 'app', scope: 'internal', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: 'ERP数据管理员', qualityScore: 69, freshness: 'Batch8小计解释审批包已生成', retention: '5年', pii: false },
  t_erp_display_approval_record_template: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '业务数据Owner', steward: '数据治理组', qualityScore: 70, freshness: 'Batch8展示审批记录模板已生成', retention: '5年', pii: false },
  t_erp_owner_approval_backlog: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch8审批backlog已生成', retention: '5年', pii: false },
  t_erp_owner_approval_intake_contract: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch9审批intake合同已生成', retention: '5年', pii: false },
  t_erp_owner_approval_validation_result: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch9审批校验结果已生成', retention: '5年', pii: false },
  t_erp_owner_approval_release_gate: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch9发布门禁已生成', retention: '5年', pii: false },
  t_erp_owner_approval_promotion_manifest: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch9 promotion manifest已生成', retention: '5年', pii: false },
  t_erp_owner_approval_owner_packet_index: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch10 owner packet index已生成', retention: '5年', pii: false },
  t_erp_owner_approval_record_input_template: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch10 owner record模板已生成', retention: '5年', pii: false },
  t_erp_owner_approval_required_evidence_matrix: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch10 required evidence矩阵已生成', retention: '5年', pii: false },
  t_erp_owner_approval_submission_readiness: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch10提交readiness已生成', retention: '5年', pii: false },
  t_erp_owner_approval_preflight_rulebook: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch11预检规则已生成', retention: '5年', pii: false },
  t_erp_owner_approval_preflight_result: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch11预检结果已生成', retention: '5年', pii: false },
  t_erp_owner_approval_forbidden_value_scan: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch11禁用值扫描已生成', retention: '5年', pii: false },
  t_erp_owner_approval_batch9_handoff_queue: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch11 Batch9 handoff队列已生成', retention: '5年', pii: false },
  t_erp_owner_approval_release_preflight_summary: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch11 release预检汇总已生成', retention: '5年', pii: false },
  t_erp_owner_submission_intake_inventory: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch12提交目录盘点已生成', retention: '5年', pii: false },
  t_erp_owner_submission_schema_audit: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch12 schema audit已生成', retention: '5年', pii: false },
  t_erp_owner_submission_redaction_audit: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch12脱敏扫描已生成', retention: '5年', pii: false },
  t_erp_owner_submission_batch11_queue: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch12 Batch11队列已生成', retention: '5年', pii: false },
  t_erp_owner_submission_release_readiness: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch12 release readiness已生成', retention: '5年', pii: false },
  t_erp_owner_submission_packet_index: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch13 submission packet index已生成', retention: '5年', pii: false },
  t_erp_owner_submission_template_manifest: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch13 template manifest已生成', retention: '5年', pii: false },
  t_erp_owner_submission_field_completion_checklist: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch13字段补全checklist已生成', retention: '5年', pii: false },
  t_erp_owner_submission_release_packet_matrix: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch13 release packet matrix已生成', retention: '5年', pii: false },
  t_erp_owner_submission_handoff_guide: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch13 handoff guide已生成', retention: '5年', pii: false },
  t_erp_owner_submission_dropbox_status: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch14 dropbox status已生成', retention: '5年', pii: false },
  t_erp_owner_submission_owner_action_queue: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch14 owner action queue已生成', retention: '5年', pii: false },
  t_erp_owner_submission_template_distribution: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch14 template distribution已生成', retention: '5年', pii: false },
  t_erp_owner_submission_release_watchlist: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch14 release watchlist已生成', retention: '5年', pii: false },
  t_erp_owner_submission_command_runbook: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch14 command runbook已生成', retention: '5年', pii: false },
  t_erp_owner_submission_acceptance_rulebook: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch15 acceptance rulebook已生成', retention: '5年', pii: false },
  t_erp_owner_submission_acceptance_result: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch15 acceptance result已生成', retention: '5年', pii: false },
  t_erp_owner_submission_evidence_uri_contract: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch15 evidence URI contract已生成', retention: '5年', pii: false },
  t_erp_owner_submission_release_acceptance_matrix: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch15 release acceptance matrix已生成', retention: '5年', pii: false },
  t_erp_owner_submission_escalation_queue: { layer: 'app', scope: 'hybrid', sensitivity: 'L3-机密', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 72, freshness: 'Batch15 escalation queue已生成', retention: '5年', pii: false },
  t_erp_owner_submission_synthetic_record: { layer: 'app', scope: 'internal', sensitivity: 'L2-内部', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 65, freshness: 'Batch16 synthetic owner records已生成', retention: '90天', pii: false },
  t_erp_owner_submission_synthetic_fixture_index: { layer: 'app', scope: 'internal', sensitivity: 'L2-内部', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 65, freshness: 'Batch16 synthetic fixture index已生成', retention: '90天', pii: false },
  t_erp_owner_submission_synthetic_record_fill_audit: { layer: 'app', scope: 'internal', sensitivity: 'L2-内部', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 65, freshness: 'Batch16 synthetic record fill audit已生成', retention: '90天', pii: false },
  t_erp_owner_submission_synthetic_gate_plan: { layer: 'app', scope: 'internal', sensitivity: 'L2-内部', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 65, freshness: 'Batch16 synthetic gate plan已生成', retention: '90天', pii: false },
  t_erp_owner_submission_synthetic_pipeline_run_matrix: { layer: 'app', scope: 'internal', sensitivity: 'L2-内部', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 65, freshness: 'Batch17 synthetic pipeline run matrix已生成', retention: '90天', pii: false },
  t_erp_owner_submission_synthetic_release_gate_matrix: { layer: 'app', scope: 'internal', sensitivity: 'L2-内部', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 65, freshness: 'Batch17 synthetic release gate matrix已生成', retention: '90天', pii: false },
  t_erp_owner_submission_synthetic_boundary_audit: { layer: 'app', scope: 'internal', sensitivity: 'L2-内部', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 65, freshness: 'Batch17 synthetic boundary audit已生成', retention: '90天', pii: false },
  t_erp_owner_real_submission_field_checklist: { layer: 'app', scope: 'internal', sensitivity: 'L2-内部', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 66, freshness: 'Batch18 real owner field checklist已生成', retention: '180天', pii: false },
  t_erp_owner_real_submission_release_gate_checklist: { layer: 'app', scope: 'internal', sensitivity: 'L2-内部', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 66, freshness: 'Batch18 real owner release gate checklist已生成', retention: '180天', pii: false },
  t_erp_owner_real_submission_swap_runbook: { layer: 'app', scope: 'internal', sensitivity: 'L2-内部', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 66, freshness: 'Batch18 real owner swap runbook已生成', retention: '180天', pii: false },
  t_erp_owner_real_submission_boundary_audit: { layer: 'app', scope: 'internal', sensitivity: 'L2-内部', status: 'pending', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 66, freshness: 'Batch18 real owner boundary audit已生成', retention: '180天', pii: false },
  t_erp_manual_release_review_record: { layer: 'app', scope: 'internal', sensitivity: 'L2-内部', status: 'governed', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 88, freshness: 'Batch19 manual release review已记录', retention: '5年', pii: false, sourceIds: erpGovernanceSourceIds },
  t_erp_manual_release_review_decision_matrix: { layer: 'app', scope: 'hybrid', sensitivity: 'L2-内部', status: 'governed', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 88, freshness: 'Batch19 decision matrix已生成', retention: '5年', pii: false, sourceIds: erpGovernanceSourceIds },
  t_erp_manual_release_review_swap_queue: { layer: 'app', scope: 'hybrid', sensitivity: 'L2-内部', status: 'governed', owner: '数据治理组', steward: '数据产品', qualityScore: 86, freshness: 'Batch19 site data swap queue已生成', retention: '5年', pii: false, sourceIds: erpGovernanceSourceIds },
  t_erp_manual_release_review_boundary_audit: { layer: 'app', scope: 'internal', sensitivity: 'L2-内部', status: 'governed', owner: '数据治理组', steward: '业务数据Owner', qualityScore: 90, freshness: 'Batch19 boundary audit已通过', retention: '5年', pii: false, sourceIds: erpGovernanceSourceIds },
};

export const changeHistory = [
  { date: '样例记录', tableId: 't_persona', action: '待接入', user: '用户研究组', desc: '用户画像需由人工凭证或CRM连接器确认', before: '未确认', after: '凭证待接入' },
  { date: '样例记录', tableId: 't_consumer_iv', action: '待接入', user: '用户研究组', desc: '消费者访谈需导入原始访谈记录', before: '未确认', after: '访谈凭证待接入' },
  { date: '样例记录', tableId: 't_porter', action: '待复核', user: '战略部', desc: '波特五力评估需人工复核', before: '旧评估', after: '人工评估待复核' },
  { date: '样例记录', tableId: 't_mkt_size', action: '复核', user: '市场分析组', desc: '市场规模随半月manifest复核，不伪造快照日期', before: '静态样例', after: '半月manifest复核' },
  { date: '样例记录', tableId: 't_comp_product', action: '排队', user: '系统', desc: 'Amazon竞品价格半月复核任务，连接器待接入', before: '-', after: '待复核记录' },
  { date: '样例记录', tableId: 't_comment', action: '待接入', user: '用户研究组', desc: '评论情感NLP需VOC凭证或连接器输入', before: '未确认', after: 'VOC凭证待接入' },
  { date: '样例记录', tableId: 't_customs', action: '待接入', user: '供应链组', desc: '海关数据需凭证或连接器导入', before: '未确认', after: '海关凭证待接入' },
  { date: '样例记录', tableId: 't_policy', action: '复核', user: '合规组', desc: '政策信息按公开来源半月复核', before: '公开页', after: '公开来源复核中' },
  { date: '样例记录', tableId: 't_social', action: '待接入', user: '社媒组', desc: '社媒声量需平台API或授权连接器', before: '未确认', after: '连接器待接入' },
  { date: '样例记录', tableId: 't_rfm', action: '待接入', user: 'CRM组', desc: 'RFM模型需CRM连接器输入', before: '未确认', after: 'CRM待接入' },
  { date: '样例记录', tableId: 't_price', action: '待接入', user: '定价组', desc: 'Amazon价格需授权连接器，不使用公开页替代', before: '未确认', after: '连接器待接入' },
  { date: '样例记录', tableId: 't_web_review', action: '待接入', user: '爬虫组', desc: '网页评论需凭证、授权爬虫或VOC流程接入', before: '未确认', after: '网页评论凭证待接入' },
  { date: '样例记录', tableId: 't_own_product', action: '待接入', user: '产品组', desc: '自有SKU和库存需ERP凭证输入', before: '未确认', after: 'ERP待接入' },
];

export const dataLineage = [
  { from: '外部研报（Grand View Research/Statista）', to: 'market_size_global', type: '外部导入' },
  { from: 'market_size_global', to: 'market_trend_monthly', type: '派生计算' },
  { from: '<span className="text-[#B5AFA8]">Amazon.com</span>', to: 'competitor_products', type: '连接器待接入' },
  { from: 'competitor_products', to: 'new_product_tracker', type: '派生计算' },
  { from: 'competitor_products', to: 'price_analysis', type: '派生计算' },
  { from: 'user_comments', to: 'comment_analysis_ai', type: 'AI分析' },
  { from: 'consumer_interviews', to: 'user_personas', type: '归纳提炼' },
  { from: 'user_personas', to: 'rfm_user_segments', type: '模型计算' },
  { from: '各国政府网站', to: 'policy_regulations', type: '公开来源复核' },
  { from: '内部ERP', to: 'momcozy_products', type: '系统同步' },
  { from: 'ERP销售/售后/零售渠道快照', to: 'erp_source_artifacts', type: '证据总账' },
  { from: 'erp_source_artifacts', to: 'erp_sales_monthly_fact', type: 'Batch19内部proxy事实' },
  { from: 'erp_source_artifacts', to: 'erp_retail_channel_monthly_fact', type: 'Batch19内部proxy事实' },
  { from: 'erp_product_sku_dim', to: 'erp_category_mapping', type: '品类归一' },
  { from: 'erp_field_dictionary', to: 'erp_display_approval_gate', type: '字段口径门禁' },
  { from: 'erp_category_mapping', to: 'category_analysis', type: '内部品类补充' },
  { from: 'erp_category_mapping', to: 'erp_category_review_queue', type: '品类人工复核' },
  { from: 'erp_category_review_queue', to: 'erp_display_approval_gate', type: '品类展示审批' },
  { from: 'erp_subtotal_reconciliation_queue', to: 'erp_display_approval_gate', type: '小计差异复核' },
  { from: 'erp_display_approval_gate', to: 'market_trend_monthly', type: 'ERP展示门禁' },
  { from: 'erp_display_approval_gate', to: 'dashboard_kpi', type: 'ERP事实发布门禁' },
  { from: 'erp_field_dictionary', to: 'erp_field_owner_approval_packet', type: '字段owner审批包' },
  { from: 'erp_category_review_queue', to: 'erp_category_owner_approval_packet', type: '品类owner审批包' },
  { from: 'erp_subtotal_reconciliation_queue', to: 'erp_subtotal_owner_explanation_packet', type: '小计解释审批包' },
  { from: 'erp_display_approval_gate', to: 'erp_display_approval_record_template', type: '展示审批记录模板' },
  { from: 'erp_display_approval_record_template', to: 'erp_owner_approval_backlog', type: '展示审批待办' },
  { from: 'erp_owner_approval_backlog', to: 'market_trend_monthly', type: 'ERP事实升级前置' },
  { from: 'erp_owner_approval_backlog', to: 'erp_owner_approval_intake_contract', type: '审批输入合同' },
  { from: 'erp_owner_approval_backlog', to: 'erp_owner_approval_record_input_template', type: 'owner记录回填模板' },
  { from: 'erp_owner_approval_intake_contract', to: 'erp_owner_approval_owner_packet_index', type: '审批包索引' },
  { from: 'erp_owner_approval_intake_contract', to: 'erp_owner_approval_required_evidence_matrix', type: '证据需求矩阵' },
  { from: 'erp_owner_approval_record_input_template', to: 'erp_owner_approval_preflight_result', type: '提交前预检' },
  { from: 'erp_owner_approval_record_input_template', to: 'erp_owner_approval_forbidden_value_scan', type: '禁用值扫描' },
  { from: 'erp_owner_approval_preflight_result', to: 'erp_owner_approval_batch9_handoff_queue', type: 'Batch9 handoff' },
  { from: 'erp_owner_approval_preflight_result', to: 'erp_owner_approval_release_preflight_summary', type: 'release预检汇总' },
  { from: 'erp_owner_approval_record_input_template', to: 'erp_owner_submission_schema_audit', type: 'owner提交schema审计' },
  { from: 'erp_owner_approval_record_input_template', to: 'erp_owner_submission_redaction_audit', type: 'owner提交脱敏审计' },
  { from: 'erp_owner_submission_schema_audit', to: 'erp_owner_submission_batch11_queue', type: 'Batch11预检队列候选' },
  { from: 'erp_owner_submission_redaction_audit', to: 'erp_owner_submission_batch11_queue', type: 'Batch11预检队列候选' },
  { from: 'erp_owner_submission_batch11_queue', to: 'erp_owner_approval_preflight_result', type: '真实提交预检' },
  { from: 'erp_owner_submission_release_readiness', to: 'erp_owner_approval_release_preflight_summary', type: '提交readiness汇总' },
  { from: 'erp_owner_approval_record_input_template', to: 'erp_owner_submission_packet_index', type: 'owner提交模板包' },
  { from: 'erp_owner_submission_packet_index', to: 'erp_owner_submission_template_manifest', type: '模板manifest' },
  { from: 'erp_owner_submission_template_manifest', to: 'erp_owner_submission_intake_inventory', type: '真实提交目录入口' },
  { from: 'erp_owner_submission_field_completion_checklist', to: 'erp_owner_submission_schema_audit', type: '字段补全检查' },
  { from: 'erp_owner_submission_release_packet_matrix', to: 'erp_owner_submission_release_readiness', type: 'release提交包映射' },
  { from: 'erp_owner_submission_handoff_guide', to: 'erp_owner_submission_intake_inventory', type: 'Batch12交接路径' },
  { from: 'erp_owner_submission_template_manifest', to: 'erp_owner_submission_dropbox_status', type: 'dropbox只读检查' },
  { from: 'erp_owner_submission_field_completion_checklist', to: 'erp_owner_submission_owner_action_queue', type: 'owner action queue' },
  { from: 'erp_owner_submission_template_manifest', to: 'erp_owner_submission_template_distribution', type: '模板分发清单' },
  { from: 'erp_owner_submission_release_packet_matrix', to: 'erp_owner_submission_release_watchlist', type: 'release watchlist' },
  { from: 'erp_owner_submission_command_runbook', to: 'erp_owner_submission_intake_inventory', type: 'Batch12命令入口' },
  { from: 'erp_owner_submission_release_watchlist', to: 'erp_owner_submission_release_readiness', type: '提交状态监控' },
  { from: 'erp_owner_submission_command_runbook', to: 'erp_owner_submission_acceptance_rulebook', type: 'acceptance规则入口' },
  { from: 'erp_owner_submission_owner_action_queue', to: 'erp_owner_submission_acceptance_result', type: 'owner提交接收检查' },
  { from: 'erp_owner_submission_field_completion_checklist', to: 'erp_owner_submission_evidence_uri_contract', type: '证据URI合同' },
  { from: 'erp_owner_submission_release_watchlist', to: 'erp_owner_submission_release_acceptance_matrix', type: 'release接收矩阵' },
  { from: 'erp_owner_submission_acceptance_result', to: 'erp_owner_submission_escalation_queue', type: 'owner升级队列' },
  { from: 'erp_owner_submission_acceptance_rulebook', to: 'erp_owner_submission_release_acceptance_matrix', type: 'release acceptance规则' },
  { from: 'erp_owner_approval_record_input_template', to: 'synthetic_owner_approval_records_batch16', type: 'synthetic fixture填充' },
  { from: 'synthetic_owner_approval_records_batch16', to: 'erp_owner_submission_synthetic_fixture_index', type: 'synthetic fixture索引' },
  { from: 'synthetic_owner_approval_records_batch16', to: 'erp_owner_submission_synthetic_record_fill_audit', type: 'synthetic填充审计' },
  { from: 'erp_owner_submission_synthetic_fixture_index', to: 'erp_owner_submission_synthetic_gate_plan', type: 'synthetic dry-run计划' },
  { from: 'erp_owner_submission_synthetic_gate_plan', to: 'erp_owner_submission_intake_inventory', type: 'Batch12 dry-run only' },
  { from: 'erp_owner_submission_synthetic_gate_plan', to: 'erp_owner_submission_synthetic_pipeline_run_matrix', type: 'Batch17 synthetic pipeline' },
  { from: 'erp_owner_submission_synthetic_pipeline_run_matrix', to: 'erp_owner_submission_synthetic_release_gate_matrix', type: 'synthetic release gate演练' },
  { from: 'erp_owner_submission_synthetic_pipeline_run_matrix', to: 'erp_owner_submission_synthetic_boundary_audit', type: 'L2边界审计' },
  { from: 'erp_owner_submission_synthetic_release_gate_matrix', to: 'erp_owner_submission_synthetic_boundary_audit', type: 'release gate边界审计' },
  { from: 'erp_owner_approval_record_input_template', to: 'erp_owner_real_submission_field_checklist', type: '真实owner回填清单' },
  { from: 'erp_owner_approval_required_evidence_matrix', to: 'erp_owner_real_submission_field_checklist', type: '必填证据映射' },
  { from: 'erp_owner_submission_release_acceptance_matrix', to: 'erp_owner_real_submission_release_gate_checklist', type: '真实release gate清单' },
  { from: 'erp_owner_submission_synthetic_boundary_audit', to: 'erp_owner_real_submission_boundary_audit', type: 'synthetic边界继承' },
  { from: 'erp_owner_real_submission_field_checklist', to: 'erp_owner_real_submission_swap_runbook', type: '真实CSV替换步骤' },
  { from: 'erp_owner_real_submission_release_gate_checklist', to: 'erp_owner_real_submission_swap_runbook', type: 'release gate替换步骤' },
  { from: 'erp_owner_real_submission_swap_runbook', to: 'erp_owner_submission_intake_inventory', type: '真实Batch12入口' },
  { from: 'erp_owner_real_submission_swap_runbook', to: 'erp_owner_approval_preflight_result', type: '真实Batch11入口' },
  { from: 'erp_owner_real_submission_swap_runbook', to: 'erp_owner_approval_validation_result', type: '真实Batch9入口' },
  { from: 'erp_owner_approval_record_input_template', to: 'erp_owner_approval_validation_result', type: '回填后校验' },
  { from: 'erp_owner_approval_submission_readiness', to: 'erp_owner_approval_release_gate', type: '提交readiness' },
  { from: 'erp_owner_approval_backlog', to: 'erp_owner_approval_validation_result', type: '审批记录校验' },
  { from: 'erp_owner_approval_validation_result', to: 'erp_owner_approval_release_gate', type: '发布门禁校验' },
  { from: 'erp_owner_approval_release_gate', to: 'erp_owner_approval_promotion_manifest', type: '事实升级候选' },
  // audit-source: ds-027 ds-047 ds-048 ds-049 ds-050 ds-051
  { from: 'erp_owner_approval_release_gate', to: 'erp_manual_release_review_record', type: 'Batch19人工release review' },
  { from: 'erp_owner_approval_promotion_manifest', to: 'erp_manual_release_review_decision_matrix', type: 'Batch19逐表决策' },
  { from: 'erp_manual_release_review_record', to: 'erp_manual_release_review_decision_matrix', type: 'manual review记录' },
  { from: 'erp_manual_release_review_decision_matrix', to: 'erp_manual_release_review_swap_queue', type: 'site data swap队列' },
  { from: 'erp_manual_release_review_record', to: 'erp_manual_release_review_boundary_audit', type: 'Batch19边界审计' },
  { from: 'erp_manual_release_review_swap_queue', to: 'market_trend_monthly', type: 'Batch19内部proxy放行' },
  { from: 'erp_manual_release_review_swap_queue', to: 'CSV exports', type: 'Batch19内部proxy导出' },
  { from: 'erp_owner_approval_release_gate', to: 'dashboard_kpi', type: 'ERP事实升级候选' },
  { from: 'erp_channel_growth_snapshot', to: 'channel_performance', type: '渠道增长补充' },
  { from: 'erp_channel_target_attainment', to: 'channel_performance', type: '目标达成补充' },
  { from: 'erp_channel_customer_dim', to: 'store_interviews', type: '渠道客户hash维表' },
  { from: 'erp_inventory_snapshot', to: 'supply_chain_nodes', type: '库存快照待授权' },
  { from: 'ai_dataset_manifest', to: 'ai_model_run_manifest', type: 'AI数据集门禁' },
  { from: 'ai_model_run_manifest', to: 'ai_human_review_gate', type: '模型运行复核' },
  { from: 'ai_human_review_gate', to: 'report_generation_queue', type: '报告生成审批' },
  { from: 'ai_erp_context_bridge', to: 'report_generation_queue', type: 'ERP上下文门禁' },
  { from: 'ai_review_sample_manifest', to: 'ai_review_eval_queue', type: '评论样本评估' },
  { from: 'ai_review_eval_queue', to: 'ai_review_human_queue', type: '模型/规则人工复核' },
  { from: 'ai_review_human_queue', to: 'ai_review_publish_gate', type: '发布审批门禁' },
  { from: 'ai_review_publish_gate', to: 'comment_analysis_ai', type: '评论/VOC事实展示门禁' },
  { from: 'ai_review_publish_gate', to: 'report_generation_queue', type: '报告引用门禁' },
  { from: 'ai_design_run_manifest', to: 'ai_design_asset_hash_manifest', type: '设计资产来源hash门禁' },
  { from: 'ai_design_run_manifest', to: 'ai_design_cost_queue', type: '设计生成成本审计' },
  { from: 'ai_design_asset_hash_manifest', to: 'ai_design_commercial_review_gate', type: '素材商用审核' },
  { from: 'ai_design_cost_queue', to: 'ai_design_commercial_review_gate', type: '成本/权利联审' },
  { from: 'ai_design_commercial_review_gate', to: 'design_assistant_output', type: '设计助手发布门禁' },
  { from: 'ai_design_commercial_review_gate', to: 'ai_gallery', type: 'AI图库发布门禁' },
  { from: 'ai_design_commercial_review_gate', to: 'report_generation_queue', type: '报告视觉资产门禁' },
  { from: 'WIPO/USPTO', to: 'ip_patents', type: 'API同步' },
];
